### ISSUE TITLE
Mobile design is less responsive

### ISSUE THREAD

**Issue by mhammadsaani** [Susmita-Dey/Sukoon#10]
There is work needed to be done for the responsiveness for this site. I can do this.

**Comment by Susmita-Dey** [comment]
But I think it's responsive @mhammadsaani

**Comment by Roshani9731** [comment]
@mhammadsaani Can I work on this issue?

**Comment by Susmita-Dey** [comment]
> @mhammadsaani Can I work on this issue?

Go ahead.

**Comment by vaibhavsharma1234** [comment]
i also want to work on this project
