### ISSUE TITLE
Footer taking too much bottom padding

### ISSUE THREAD

**Issue by itsmdasifraza** [Susmita-Dey/Sukoon#107]
Footer bottom padding is too large, you can see in the given picture, 
I will also add .png logo in footer after removing white background of logo

![Screenshot (99)](https://user-images.githubusercontent.com/58258334/183302140-4e621172-9d56-4ea4-9e3b-5d31a992ee5b.png)

**Comment by itsmdasifraza** [comment]
I will also add .png logo in footer after removing white background of logo

**Comment by imaaquibali** [comment]
@itsmdasifraza Start working on it.
