### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by 2024-SANDHYA** [Susmita-Dey/Sukoon#11]
I want to add the favicon to the webpage, to make it look more professional. @Susmita-Dey

**Comment by kakkarot0** [comment]
hey can i work on this issue

**Comment by Susmita-Dey** [comment]
@2024-SANDHYA Do you want to take it over or shall I assign it to @kakkarot0 ?

**Comment by 2024-SANDHYA** [comment]
I would like to take it @Susmita-Dey

**Comment by Susmita-Dey** [comment]
> I would like to take it @Susmita-Dey 

Go ahead. @kakkarot0 Sandhya is doing the work if she fails then I'd assign it to you later on
