### ISSUE TITLE
Laughing Therapy Page

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#113]
I will create the complete page of laughing therapy with all the relevant information, how to perform, benefits ...
So can you Assign it to me?

SSOC'22
![Screenshot 2022-08-08 103735](https://user-images.githubusercontent.com/89779447/183343465-359ebb39-cb35-4da2-a994-c65158e54ce1.png)

**Comment by SachinMittal1766** [comment]
@MohitNamdev22 Go Ahead

**Comment by MohitNamdev22** [comment]
I'm closing this issue because it has been assigned to someone else earlier, Sorry for the inconvenience
