### ISSUE TITLE
Removing the white space from page footer

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#118]
I have attached a Screenshot, as you can see the white space at the bottom of the page looks bad. I want to fix this under SSOC'22.
Can you please assign it to me?
![Screenshot 2022-08-08 123715](https://user-images.githubusercontent.com/89779447/183360041-5537dfaa-8e51-4d2b-a0eb-9384a39fc324.png)

**Comment by Susmita-Dey** [comment]
Check issue #107 
It's a duplicate issue. I've to close it. You can go and comment there. If the person assigned fails to complete, then you'll get assigned.

**Comment by MohitNamdev22** [comment]
Okay Sure!
