### ISSUE TITLE
[FEATURE] Add login button to website

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#119]
Add login/sign in button to the website in the right hand corner.

**Comment by 09khu** [comment]
I want to work it on

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by Vignesh2131** [comment]
I haven't started yet so please assign it to me

**Comment by Susmita-Dey** [comment]
@Vignesh2131 go ahead

**Comment by Vignesh2131** [comment]
for the confirmation, the issue is adding only the login and sign-in button in the navbar. Is that it?
