### ISSUE TITLE
Improving UI of the website.

### ISSUE THREAD

**Issue by dare-devilll** [Susmita-Dey/Sukoon#12]
Can I work on improving the UI and adding some nice animations to the website?

**Comment by Susmita-Dey** [comment]
@dare-devilll Can you show me what improvements or changes you have on your mind by showing a template of your idea?

**Comment by dare-devilll** [comment]
I don't have a template right now but I want to add some animations to the cards, like some flip transitions, dashboard transitions, and hover effects on buttons, and improve the color scheme.
Making a design template with animations is hard for me...can I code and show it to you?

**Comment by Susmita-Dey** [comment]
> I don't have a template right now but I want to add some animations to the cards, like some flip transitions, dashboard transitions, and hover effects on buttons, and improve the color scheme.
> Making a design template with animations is hard for me...can I code and show it to you?

Yes code it and show it to me

**Comment by vandana3869** [comment]
Can I work on its UI enhancement and logo designing

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Can I work on its UI enhancement and logo designing

Show me the template of the changes you wanna make

**Comment by Susmita-Dey** [comment]
@vandana3869 and @dare-devilll First show me a template of the changes you wanna make and then I'll choose and will tell you to create a PR

**Comment by vandana3869** [comment]
@Susmita-Dey  here is the demo template ....we enhance while actual coding
https://sukoon.my.canva.site/

**Comment by dare-devilll** [comment]
@Susmita-Dey I am currently coding the animations for the team and service section and as I told it's hard to show animations in a template...give me 3-4 days to show the final product.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey I am currently coding the animations for the team and service section and as I told it's hard to show animations in a template...give me 3-4 days to show the final product.

Take you time

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey here is the demo template ....we can enhance it more while actual coding https://sukoon.my.canva.site/

The site looks awesome but some improvements are needed. Let's wait for @dare-devilll and I'll confirm both of you then after that.

**Comment by nandinitrivedi05** [comment]
Hey, I am working on this in a few hours I will send you the demo temp.

**Comment by nandinitrivedi05** [comment]
So, here's the link : https://hhtp.my.canva.site/

**Comment by Susmita-Dey** [comment]
> So, here's the link : https://hhtp.my.canva.site/

Many things need improvement. Some of them are like:
- text color
- navbar
- contact section

**Comment by YasirObaibullah99** [comment]
I can improve the text color,navbar and contact section

**Comment by radzhiv25** [comment]
Will improve this websites UI by taking reference from behance or dribbble.

**Comment by Susmita-Dey** [comment]
@vandana3869 @radzhiv25 @YasirObaibullah99 @nandinitrivedi05 Are you all SSOC participant?

**Comment by radzhiv25** [comment]
> @vandana3869 @radzhiv25 @YasirObaibullah99 @nandinitrivedi05 Are you all SSOC participant?

Yes SSOC participant

**Comment by dare-devilll** [comment]
@Susmita-Dey I am also in the SSOC.

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey I am also in the SSOC.

I can't assign it to you now

**Comment by vandana3869** [comment]
> @vandana3869 @radzhiv25 @YasirObaibullah99 @nandinitrivedi05 Are you all SSOC participant?

Yes

**Comment by nandinitrivedi05** [comment]
> > @vandana3869 @radzhiv25 @YasirObaibullah99 @nandinitrivedi05 Are you all SSOC participant?
> 
> Yes SSOC participant

> Yes !!

**Comment by YasirObaibullah99** [comment]
@Susmita-Dey I am also in the SSOC.
