### ISSUE TITLE
Make the Services section responsive

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#121]
The text is overlapping the image
![Screenshot_20220808-125730](https://user-images.githubusercontent.com/94471189/183364049-0f79123f-b3c0-4fea-b13d-48674470a4e7.jpg)

**Comment by Susmita-Dey** [comment]
Good observation. Go ahead

**Comment by Vanshiii203** [comment]
I have one small doubt, for fixing this do I have to re-fork the repository? because this issue appeared after the merge of a PR

**Comment by Susmita-Dey** [comment]
> I have one small doubt, for fixing this do I have to re-fork the repository? because this issue appeared after the merge of a PR

No just fetch and pull the changes done before making any changes and pushing to the repository back

**Comment by Vanshiii203** [comment]
Ok thanks!

**Comment by itsmdasifraza** [comment]
@Vanshiii203  Please mention this issue in your pull request using #
