### ISSUE TITLE
Improving the Heading Font Family & Font Size of About Us Section

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#123]
The font family & size of the heading of the about section not looking good, and the previous contributors worked on the transition & aesthetics, not on the Heading. So can you assign me to work on the Heading of About Section?

![Screenshot_11](https://user-images.githubusercontent.com/89779447/183374723-92aac776-e215-45c0-8b28-363a4647c0b6.png)

**Comment by Susmita-Dey** [comment]
Go ahead
