### ISSUE TITLE
The navbar is overlapping with main section of Mobile Layout

### ISSUE THREAD

**Issue by SujalSamai** [Susmita-Dey/Sukoon#124]
We need to add some css and Javascript to this section so that it doesn't get overlapped.
![Screenshot_2022-08-08-14-03-59-39_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87236576/183376157-045818de-6d22-4b8e-b11d-de4eab50fc9a.jpg)

**Comment by Susmita-Dey** [comment]
Go ahead
