### ISSUE TITLE
Update text in FAQ section.

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#132]
Fixing the grammatical errors in FAQ section.
![Screenshot (293)](https://user-images.githubusercontent.com/94471189/183403271-461dea72-20cb-4806-8626-15bd481ee3b6.png)

**Comment by Susmita-Dey** [comment]
Do you wanna change that `on` to `at` in that section?

**Comment by Vanshiii203** [comment]
> Do you wanna change that `on` to `at` in that section?

Yes! I would also like to improve the way some questions are answered.

**Comment by Susmita-Dey** [comment]
> Yes! I would also like to improve the way some questions are answered.

First change the title of this issue to `Update text in FAQ section.`
Then I'll assign it to you.

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Have you completed your previously assigned issues?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Have you completed your previously assigned issues?

I have to make the changes that were asked in my PR.

**Comment by Susmita-Dey** [comment]
> I have to make the changes that were asked in my PR.
Complete it first and then start working on it.
