### ISSUE TITLE
Heading is overlapping navbar in mobile view

### ISSUE THREAD

**Issue by ArunaAT** [Susmita-Dey/Sukoon#134]
![1](https://user-images.githubusercontent.com/98509070/183426894-86741a52-3522-4259-8401-d4a813ff35bc.PNG)
you can correct it by z-index

.menu .open{
z-index:1;
}

**Comment by Susmita-Dey** [comment]
@ArunaAT Check issue #124 
This is a duplicate issue. You can go and comment there.
If the person assigned there fails then you would be assigned next.
