### ISSUE TITLE
Improve Cards of Audiobooks

### ISSUE THREAD

**Issue by Shivam-Katare** [Susmita-Dey/Sukoon#135]
I think we can add and improve this card section. Here we can add these audiobooks with more animations. Like some hover effects, and I would love to work on this issue.

![08 08 2022_19 53 22_REC](https://user-images.githubusercontent.com/91705825/183441164-afff17dc-e084-4441-8a59-755b657a1dad.png)

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Go ahead
