### ISSUE TITLE
Title not displayed properly in the reading therapy website

### ISSUE THREAD

**Issue by popcandy1x** [Susmita-Dey/Sukoon#136]
In the reading therapy website the title at the top of browser window is not displayed correctly.Instead of showing Sukoon name and its favicon it shows 'Document' along with no favicon.
![Screenshot 2022-08-08 at 8 05 37 PM](https://user-images.githubusercontent.com/81379049/183445440-45893f7a-0bcb-4535-81bd-98f500a49624.png)
I would like to fix the issue and make the title display 'Sukoon' and its favicon.

**Comment by Susmita-Dey** [comment]
@popcandy1x Go ahead
