### ISSUE TITLE
Bug: Signup page has no input validation

### ISSUE THREAD

**Issue by itsmdasifraza** [Susmita-Dey/Sukoon#140]
Input validations must be required...

**Comment by Susmita-Dey** [comment]
Describe more what do you wanna add

**Comment by itsmdasifraza** [comment]
@Susmita-Dey  I will add email validation, password validation, and name field
please assign

**Comment by itsmdasifraza** [comment]
![183456059-c99cea1d-94aa-4bca-82a0-1580bac35205](https://user-images.githubusercontent.com/58258334/183459096-a32436c9-8c39-41f8-9df0-3200ba172e02.png)

**Comment by Susmita-Dey** [comment]
@itsmdasifraza Go ahead
