### ISSUE TITLE
Login button cursor problem 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/Sukoon#141]

**Comment by AnshuPathak-88825** [comment]
login button should be cursor pointer

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by myhacktech** [comment]
> pls assign me this issue

link has to be attached,to which u are referring to bcz many such pages will be designed in upcoming time, please follow instructions

**Comment by Susmita-Dey** [comment]
@myhacktech He had found a good point.

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Good observation. Go ahead.

**Comment by AnshuPathak-88825** [comment]
thanks

**Comment by AnshuPathak-88825** [comment]
there's was one more problem if click corner of button then anchor tag won't work I've solved that issue too

**Comment by AnshuPathak-88825** [comment]
pls merge this pr
