### ISSUE TITLE
Improving audiotherapy Page UI, Design, adding Caursal

### ISSUE THREAD

**Issue by Anubhavgupta14** [Susmita-Dey/Sukoon#143]
Improving audiotherapy Page UI, Design,

**Comment by ShivanshAr97** [comment]
Please see it does not clash with issue #116 🙂

**Comment by Anubhavgupta14** [comment]
@ShivanshAr97 I have only changed the background of header in that page, you can go ahead.

**Comment by Susmita-Dey** [comment]
Duplicate issue #57
