### ISSUE TITLE
Making the Navbar on Audio Page responsive

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#147]
![Screenshot 2022-08-09 003232](https://user-images.githubusercontent.com/97726887/183494164-c95eabf1-52d8-496f-9f2a-f9245c2ba5fb.png)

- The Navbar on audio Page is not responsive.

**Comment by SahilDahekar** [comment]
can I take up this Issue ?

**Comment by Susmita-Dey** [comment]
@SahilDahekar Go ahead

**Comment by SahilDahekar** [comment]
yep

**Comment by ShivanshAr97** [comment]
I have taken care of this issue in issue #116. Please see once.

**Comment by SahilDahekar** [comment]
@ShivanshAr97 Your PR got merged but it still got issues and also i have added additional feature of toogling the hamburger svg with cross svg.
