### ISSUE TITLE
Changing Background of Our Team.

### ISSUE THREAD

**Issue by Anubhavgupta14** [Susmita-Dey/Sukoon#149]
Changing Background of Our Team.(Animation)

https://user-images.githubusercontent.com/97956667/183501934-22eb581b-fdb4-4ea7-b01b-9f451d239b25.mp4

**Comment by Anubhavgupta14** [comment]
@Susmita-Dey  Assign me so that I can raise PR for this change.

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 Sorry but this animation won't look professional. Closing this as not planned.
