### ISSUE TITLE
Improvement in the UI of Contact Us Form

### ISSUE THREAD

**Issue by vaibhavchaubey** [Susmita-Dey/Sukoon#15]
Can I work on improving the UI of the Contact Us Form and adding some nice styling to it?

**Comment by radzhiv25** [comment]
Will improve the UI by taking reference from behance or dribble 
Will be glad if it gets assigned soon

**Comment by Cypher1002** [comment]
would like to work on this issue adding more styles and improving the user experience by using fonts and animation and hover effects to look the contact us  forms more appealing to audience and also fix the buttons

**Comment by Cypher1002** [comment]
@Susmita-Dey yes want to work over it under ssoc

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey yes

I can't assign it to you now

**Comment by vaibhavchaubey** [comment]
> @vaibhavchaubey @Cypher1002 @radzhiv25 Are you all SSOC participant?

Yes. Please assign me the issue
