### ISSUE TITLE
Making email link responsive and enhancing design of social media icons [SSOC]

### ISSUE THREAD

**Issue by keerthana054** [Susmita-Dey/Sukoon#151]

**Comment by Susmita-Dey** [comment]
@keerthana054 What do you mean by email link responsive?
Can you share the screenshot of the bug?

**Comment by myhacktech** [comment]
> @keerthana054 What do you mean by email link responsive? Can you share the screenshot of the bug?

she also wants to work on sociaal media icon

**Comment by Susmita-Dey** [comment]
> she also wants to work on sociaal media icon
I know but since she mentioned 2 things, we must be aware of both the changes she wanna make.

**Comment by myhacktech** [comment]
@keerthana054 

> > she also wants to work on sociaal media icon
> 
> I know but since she mentioned 2 things, we must be aware of both the changes she wanna make.

**Comment by myhacktech** [comment]
> @keerthana054
> 
> > > she also wants to work on sociaal media icon
> > 
> > 
> > I know but since she mentioned 2 things, we must be aware of both the changes she wanna make.

@keerthana054 always add screenshot and link of the changes you wish to make

**Comment by keerthana054** [comment]
> @keerthana054 What do you mean by email link responsive? Can you share the screenshot of the bug?

https://user-images.githubusercontent.com/91015385/183562974-08e8e3b3-9156-4145-82fa-86a880e4af7b.mp4

**Comment by keerthana054** [comment]
> > @keerthana054
> > > > she also wants to work on sociaal media icon
> > > 
> > > 
> > > I know but since she mentioned 2 things, we must be aware of both the changes she wanna make.
> 
> @keerthana054 always add screenshot and link of the changes you wish to make

Okay sir!

**Comment by myhacktech** [comment]
> > @keerthana054 What do you mean by email link responsive? Can you share the screenshot of the bug?
> 
>  Sukoon.-.Google.Chrome.2022-08-09.09-44-56.mp4
that s not responsive
i think u want to make it active..right?

**Comment by keerthana054** [comment]
> > > @keerthana054 What do you mean by email link responsive? Can you share the screenshot of the bug?
> > 
> > 
> > Sukoon.-.Google.Chrome.2022-08-09.09-44-56.mp4
> > that s not responsive
> > i think u want to make it active..right?

yes sir.

**Comment by keerthana054** [comment]
> > > @keerthana054 What do you mean by email link responsive? Can you share the screenshot of the bug?
> > 
> > 
> > Sukoon.-.Google.Chrome.2022-08-09.09-44-56.mp4
> > that s not responsive
> > i think u want to make it active..right?

Can I also change the name Video therapy to Laughing therapy? as video therapy is not available in services.

**Comment by myhacktech** [comment]
> > > > @keerthana054 What do you mean by email link responsive? Can you share the screenshot of the bug?
> > > 
> > > 
> > > Sukoon.-.Google.Chrome.2022-08-09.09-44-56.mp4
> > > that s not responsive
> > > i think u want to make it active..right?
> 
> Can I also change the name Video therapy to Laughing therapy? as video therapy is not available in services.

i didn't get ur point..

**Comment by Susmita-Dey** [comment]
@keerthana054 It's a seperate issue which must be created if there are no duplicate issues. For now Wwork on this particular issue.
