### ISSUE TITLE
The Bottom to Up button doesn't have cursor pointer property & Hover effect

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#152]
I want to work on this issue and give a pointer & hover effect to the bottom to up button. So can you assign this issue to me?
![Screenshot_13](https://user-images.githubusercontent.com/89779447/183565570-9ac6ecf0-fcb9-4674-bf7f-a8f9b3b9ec52.png)

SSOC'22

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 How many issues are left which have been assigned to you?

**Comment by MohitNamdev22** [comment]
No issues are left from yesterday, this one is first issue of the day

**Comment by MohitNamdev22** [comment]
All previous issues are completed & merged, So can you assign it to me?

**Comment by Susmita-Dey** [comment]
> All previous issues are completed & merged, So can you assign it to me?

Go ahead
