### ISSUE TITLE
Images in Our services section are getting overlapped at 870px to 700px

### ISSUE THREAD

**Issue by Vignesh2131** [Susmita-Dey/Sukoon#158]
While checking for responsiveness there is a minor bug during the minimization of the website.
So I want to work on this.
Please assign me this issue
![2022-08-09 (2)](https://user-images.githubusercontent.com/96634914/183595375-e06e178b-9997-4d66-8e7a-e433e68154ca.png)
.

**Comment by Susmita-Dey** [comment]
@Vignesh2131 I just checked the website. It's working fine. No such issues that you;re mentioning. Kindly do git fetch and git pull and merge the chanegs to see the changes made to the website locally.
Closing this now.
