### ISSUE TITLE
Removing extra height from the logo

### ISSUE THREAD

**Issue by dare-devilll** [Susmita-Dey/Sukoon#159]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/92071471/183626803-6d7eba52-7585-4313-9f34-39c2abbf9d53.png">

**Comment by dare-devilll** [comment]
I am working on the navbar and solving this issue will help me.

**Comment by Susmita-Dey** [comment]
@dare-devilll Go ahead

**Comment by dare-devilll** [comment]
I already made a pr, can you check?

**Comment by Susmita-Dey** [comment]
> I already made a pr, can you check?

Yes, checking

**Comment by dare-devilll** [comment]
can I close the issue?
