### ISSUE TITLE
improving UI of audio therapy page

### ISSUE THREAD

**Issue by kshitijmishra27** [Susmita-Dey/Sukoon#16]
hey @Susmita-Dey 
on the audio therapy page 
I wanted to change the colour of texts "music" and "stress relief sounds" to white as it will look good with green colour and also I will add hover effect with white background to nav bar and these texts....it will make your website look cool 😄😄

as soon as you assign me I am ready to work for it 😄

**Comment by radzhiv25** [comment]
Can work on this and will improve it

**Comment by Cypher1002** [comment]
would like to work on the issue and improve it a lot

**Comment by Susmita-Dey** [comment]
> hey @Susmita-Dey on the audio therapy page I wanted to change the colour of texts "music" and "stress relief sounds" to white as it will look good with green colour and also I will add hover effect with white background to nav bar and these texts....it will make your website look cool 😄😄
> 
> as soon as you assign me I am ready to work for it 😄

Are you an SSOC participant?

**Comment by kshitijmishra27** [comment]
yup
