### ISSUE TITLE
Improving the UI of About Us section of the website

### ISSUE THREAD

**Issue by undextered** [Susmita-Dey/Sukoon#163]
The about us section of the website does not feel consistent with the whole website so I would like to change it.

**Comment by Susmita-Dey** [comment]
Describe more what changes you wanna make

**Comment by imaaquibali** [comment]
@undextered Can you please describe more about your issue?

**Comment by undextered** [comment]
The images look warped and the cards are too big. It lacks design, the border also looks ugly. In conclusion, I would like to revamp that to match the whole design of the website
