### ISSUE TITLE
Improving the responsiveness of home page

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#167]
1. Responsiveness is not properly done.

![Screenshot 2022-08-09 223040](https://user-images.githubusercontent.com/97726887/183713149-530907bf-038f-4326-9c38-10e1c1c10fde.png)
![Screenshot 2022-08-09 223157](https://user-images.githubusercontent.com/97726887/183713138-0df2493f-b81f-4055-9d3d-8efe1aebfc46.png)

2. Back to top button is getting overlapped by elements inside About section.

![Screenshot 2022-08-09 223108](https://user-images.githubusercontent.com/97726887/183713144-ca19cb0c-4d2b-48d5-a176-513fedf9ae88.png)

**Comment by SahilDahekar** [comment]
hey i want to work on this issue can u assign this to me?

**Comment by SachinMittal1766** [comment]
@SahilDahekar Assigned

**Comment by myhacktech** [comment]
updates ?
