### ISSUE TITLE
Adding responsiveness to the Subheading of About Us Page

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#169]
The sub-heading of the about us page isn't responsive, so can I fix this issue?

![image](https://user-images.githubusercontent.com/89779447/183815393-5ddd91d6-f1c6-474f-b0e5-98e3464c9bd5.png)

**Comment by imaaquibali** [comment]
@MohitNamdev22 Start working on it 👍
