### ISSUE TITLE
To improvement in UI( Font and Color)

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#17]
In audiothereapy section, the text used is not clearly visible and mismatched with its background, so I would like to change the color and font of a given text. So assigned me.

![SSOC issue 1](https://user-images.githubusercontent.com/87818185/182157528-671f8e13-8970-4b2a-b04e-3d7d6d1577a4.png)

**Comment by Cypher1002** [comment]
i would like to work on this issue will change the font using google fonts and enchance the colours using a gradient color shades and make it look more user frendly

**Comment by Susmita-Dey** [comment]
> i would like to work on this issue will change the font using google fonts and enchance the colours using a gradient color shades and make it look more user frendly

Are you an SSOC participant?

**Comment by vaibhavsharma1234** [comment]
i like to improve profile cards on main page can i do it i am a ssoc participant
