### ISSUE TITLE
Homogeneity missing in the text [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#175]
Homogeneity in the text content is missing in "Our Services" section

![ss](https://user-images.githubusercontent.com/96040322/184002237-a1ab9389-bb19-48d8-90db-91e283452b08.jpg)

(For SSOC Contribution)

**Comment by ShivanshAr97** [comment]
Please assign it to me !

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Do you wanna change the button text or the picture?

**Comment by ShivanshAr97** [comment]
Yes! Changing the button text of "Talking Therapy" (I have indicated with arrow)

It should match with other buttons

**Comment by ShivanshAr97** [comment]
Please assign if possible?

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 go ahead
