### ISSUE TITLE
fix headSection UI

### ISSUE THREAD

**Issue by con-artist** [Susmita-Dey/Sukoon#176]
![image](https://user-images.githubusercontent.com/82517773/184067511-25e7e5e3-a0ce-4cce-bbbd-774eabf4b607.png)
I want to fix this

**Comment by Susmita-Dey** [comment]
@con-artist Image didn't uploaded properly.

**Comment by con-artist** [comment]
Check now

**Comment by Susmita-Dey** [comment]
@con-artist Go ahead
