### ISSUE TITLE
Improvement in Navbar 

### ISSUE THREAD

**Issue by radzhiv25** [Susmita-Dey/Sukoon#18]
Will redesign the navbar

**Comment by Susmita-Dey** [comment]
> Will redesign the navbar

Are you an SSOC participant?

**Comment by radzhiv25** [comment]
> > Will redesign the navbar
> 
> 
> 
> Are you an SSOC participant?

Yes I am SSOC participant

**Comment by Susmita-Dey** [comment]
@radzhiv25 Sorry I can't assign it you now since the contribution has not started yet. Closing this now.
