### ISSUE TITLE
Maintaining consistency across all home page card.

### ISSUE THREAD

**Issue by dare-devilll** [Susmita-Dey/Sukoon#182]
Different contributor developed the cards, so I think the cards need to have one particular theme, which remains consistent across
the website, I want to work on it.

**Comment by dare-devilll** [comment]
I really liked the theme of the talking therapy cards, I want to create something like that.
Also, I will try to make colors matching the logo rotate around the cards on the border.
Let's see if it's possible🤞🏻

**Comment by dare-devilll** [comment]
can I do it?

**Comment by imaaquibali** [comment]
@dare-devilll Do it man!
