### ISSUE TITLE
Want to improve Signup and Login page

### ISSUE THREAD

**Issue by thisisamanmishra** [Susmita-Dey/Sukoon#185]

**Comment by AnshuPathak-88825** [comment]
assign me this issue

**Comment by thisisamanmishra** [comment]
@AnshuPathak-88825 Hey, I want to work on this that's why I've raise this issue

**Comment by AnshuPathak-88825** [comment]
ok no problem

**Comment by Susmita-Dey** [comment]
@thisisamanmishra Do you wanna improve the UI of signup and login page?

**Comment by thisisamanmishra** [comment]
@Susmita-Dey Yes

**Comment by Susmita-Dey** [comment]
@thisisamanmishra A PR with the backend of signup login page is already awaiting. 
Can you kindly hold on for some days before the PR gets merged?
I'm asking this beacuse it will create a mess later on with the frontend and backend part.

**Comment by thisisamanmishra** [comment]
@Susmita-Dey okay no issue
