### ISSUE TITLE
Want to add scrolling feature in Talking Therapy in html page

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/Sukoon#186]

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825  Do you mean smooth-scrolling?

**Comment by AnshuPathak-88825** [comment]
yes

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 Go ahead

**Comment by AnshuPathak-88825** [comment]
[Screencast from 14-08-22 06:49:47 PM IST.webm](https://user-images.githubusercontent.com/78332454/184539041-7b6b0349-a9cd-4151-8666-0998aa0fb7f0.webm)

I've added smooth scrolling feature to every file
