### ISSUE TITLE
lets explore button in services section should be in same line

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/Sukoon#187]

**Comment by AnshuPathak-88825** [comment]
![Screenshot (343)](https://user-images.githubusercontent.com/78332454/184108336-82740f13-edf5-481d-8272-d20010bf3b18.png)

I want to make let's explore button in same line

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by imaaquibali** [comment]
@AnshuPathak-88825 start working!
