### ISSUE TITLE
Improve UI using gradient colour

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/Sukoon#188]

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by Susmita-Dey** [comment]
@AnshuPathak-88825 What gradient colors do you wanna use and which section's UI do you wanna change?

**Comment by imaaquibali** [comment]
@AnshuPathak-88825 can you explain bit more?

**Comment by imaaquibali** [comment]
@AnshuPathak-88825 If you working on this issue please let me know. otherwise i will close this issue XD

**Comment by AnshuPathak-88825** [comment]
you can close it
