### ISSUE TITLE
Fixing the link in audio therapy page logo

### ISSUE THREAD

**Issue by Surya8991** [Susmita-Dey/Sukoon#190]
[SSOC 2022 Participant]
As You can see the link in both the home button and logo to home page is different and when we click on the logo we get an error saying page not found so I would like to fix this bug by changing the link in the logo to point to the home page.

![image](https://user-images.githubusercontent.com/85568108/184111955-3fba2d57-492e-4216-b893-41f93ed871ca.png)
![image](https://user-images.githubusercontent.com/85568108/184112049-e61278f8-f0ff-4f85-9341-bec01f921b25.png) 
![image](https://user-images.githubusercontent.com/85568108/184112329-00619f3c-c2ca-44c1-a7a3-7f0f20902014.png)

**Comment by Susmita-Dey** [comment]
@Surya8991 Good observation. Go ahead

**Comment by Surya8991** [comment]
Sure
