### ISSUE TITLE
Fixing the logo link in Reading and Talking therapy Page

### ISSUE THREAD

**Issue by Surya8991** [Susmita-Dey/Sukoon#192]
I would like to fix the logo link issue in Reading and Talking therapy Page
![image](https://user-images.githubusercontent.com/85568108/184123577-1261e09e-1422-4070-8dfc-e04078915049.png)
![image](https://user-images.githubusercontent.com/85568108/184123632-a9a913b8-3a25-4ad7-a27a-01de9dba55df.png)

**Comment by imaaquibali** [comment]
@Surya8991 Start working!

**Comment by Surya8991** [comment]
Ok

**Comment by Surya8991** [comment]
closing issue as the changes have been made. And I couldn't do because i was busy.
