### ISSUE TITLE
Improve the font family of FaQ Section

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#201]
In the FaQ Section Heading, Sub-Heading, and Description all have the same font family and it seems attractive. So can I work on this?

![image](https://user-images.githubusercontent.com/89779447/184292660-675b3cd9-ca5a-4799-ba3c-180961e3102d.png)

**Comment by imaaquibali** [comment]
@MohitNamdev22 go for it.
