### ISSUE TITLE
The login and signup button doesn't have cursor pointer property & Hover effect

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#209]
![Screenshot (316)](https://user-images.githubusercontent.com/94471189/184474945-3a785ff2-5add-447f-8e23-198077e25aa5.png)

**Comment by imaaquibali** [comment]
@Vanshiii203 Do it. Try to add hover button like [this](https://github.com/imaaquibali/Color-Button-Animation)
