### ISSUE TITLE
Hyperlinking sukoon email at the footer section

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#210]
The mail address present at the footer is only in typed form, it can be hyperlinked with mail to ( Email ). Then it would be easy for the user to mail. So can I work on this?

![image](https://user-images.githubusercontent.com/89779447/184475139-1fbdb3b9-f69d-41e9-97f2-a282842c3266.png)

**Comment by myhacktech** [comment]
this issue already assigned,someone is working on this

**Comment by myhacktech** [comment]
i m closing this
