### ISSUE TITLE
Improve UI of the Reading Therapy Page

### ISSUE THREAD

**Issue by SujalSamai** [Susmita-Dey/Sukoon#215]
I would like to improve the readability, background colors, and alignment of the Reading Therapy Page and will work on bringing it to a symmetry to the audio therapy page. Right now both the pages look too different from each other (font sizes, color combination etc.)
![image](https://user-images.githubusercontent.com/87236576/184501212-211ec644-42d2-4a1a-949c-87a8544fe54c.png)

**Comment by Atharv-110** [comment]
Go aheah @SujalSamai, Assigned to you.

**Comment by popcandy1x** [comment]
I have already worked upon this issue and fixed it in a previous issue:-
issue:-https://github.com/Susmita-Dey/Sukoon/issues/80

**Comment by popcandy1x** [comment]
Sorry to say but do you guys even check before assigning people to issues without addressing and merging the previous prs

**Comment by Atharv-110** [comment]
@SujalSamai this was assigned already, my bad.
You can work on other issues.
