### ISSUE TITLE
Improving footer section

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#222]
I would like to improve the footer section of website. [SSOC contribution]
By adding the new logo, improving font size of text and increasing size of icons, removing underline and adding better hover effects.

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/184528094-85802670-8fb6-4e15-855e-2155c2a995d9.png)

**Comment by ShivanshAr97** [comment]
Please assign it to me!

**Comment by myhacktech** [comment]
issue of this type already assigned
