### ISSUE TITLE
Making sticky navbar

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#227]
I would like to make a sticky navbar so that it is visible even when the page is scrolled down.

For SSOC Contribution.

**Comment by ShivanshAr97** [comment]
Please assign it to me!

**Comment by imaaquibali** [comment]
@ShivanshAr97 Go for it.

**Comment by AliReza1083** [comment]
@ShivanshAr97 
Try to make a navbar that when someone `scrolls downward`, the navbar disappear and when the someone `scrolls upward`, the navbar should appear.
It'll be great.
