### ISSUE TITLE
Improving the testimonials section [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#236]
I would like to improve the testimonial section like adding hover and focus effects, improving font size and text, 

For SSOC contributions

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/184646517-73ea28f0-867c-49d3-84ef-afdf70430639.png)

**Comment by ShivanshAr97** [comment]
Please assign it to me!

**Comment by siddhi-244** [comment]
I think it is already made by someone

**Comment by Susmita-Dey** [comment]
> I think it is already made by someone

Is it a duplicate issue?
> If yes, then close it with the label `duplicate` and `ssoc`
