### ISSUE TITLE
Making navbar of reading therapy page responsive

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#248]

**Comment by Susmita-Dey** [comment]
@Vanshiii203 screenshot please

**Comment by Vanshiii203** [comment]
@Susmita-Dey 
![Screenshot (325)](https://user-images.githubusercontent.com/94471189/185584990-db83e0a2-df4d-4bec-aaee-8c3cde579487.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Go ahead
