### ISSUE TITLE
Sevices in footer aren't hyperlinked to respective pages.

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#249]
In the footer section the links of services like audio therapy, reading therapy, etc. Are not redirecting to respective pages. So, can I fix this issue under SSOC'22?

![image](https://user-images.githubusercontent.com/89779447/185566064-07f06db8-e2a6-4204-93f6-cf044f7c6fb7.png)

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Have you checked for duplicate issues?

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Go ahead
