### ISSUE TITLE
Making the service section Responsive..

### ISSUE THREAD

**Issue by AliReza1083** [Susmita-Dey/Sukoon#250]
For tablet Device this might make a problem.
So, I want to fix this Issue.

Please assign it to me.

![image](https://user-images.githubusercontent.com/99729607/185574392-31edc29f-7b25-45dd-9292-fa9d7c2be629.png)

**Comment by Susmita-Dey** [comment]
@AliReza1083 Have you fetched and merged the changes made recently to the website?

If no, then do it first. To me it's been already fixed. If any further issues lies, report to me again,

**Comment by AliReza1083** [comment]
can I fix this issue?

**Comment by AliReza1083** [comment]
For tablet device, it is 3 columns, So if it was 2 columns, it would be great.

Please assign to me to fix it.
![image](https://user-images.githubusercontent.com/99729607/185580631-3cf9d180-0b20-4344-8f1a-6228d8d103ff.png)

**Comment by Susmita-Dey** [comment]
@AliReza1083 Go ahead
