### ISSUE TITLE
[DUPLICATE ITEMS] Footer items duplicate

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#252]
Delete duplicate items from the footer.
- Services
- Contact
These 2 things are replicated in the footer.
![image](https://user-images.githubusercontent.com/79099734/185582520-931d9678-3bf9-4766-a1da-8073478e8764.png)

**Comment by ShivanshAr97** [comment]
You can assign it to me

**Comment by MohitNamdev22** [comment]
Can I work on this?

**Comment by Vanshiii203** [comment]
Can I work on this?

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 @Vanshiii203 Since @ShivanshAr97 commented first, I've to assign it to him

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Go ahead
