### ISSUE TITLE
Making a customized scroll bar [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#253]
I would like to make a designed scroll bar rather than the default scroll bar

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/185583407-e99b1f11-cb42-435e-b445-54b28c05ffa8.png)

**Comment by ShivanshAr97** [comment]
please assign it to me

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Go ahead
