### ISSUE TITLE
Improvement in UI of coming soon page

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#258]
I would like to improve the interface of coming soon page which looks pretty childish and unprofessional and is not functioning properly as well.

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/185596808-2ff96e3b-ab39-4b79-bfff-21169f54897e.png)

**Comment by ShivanshAr97** [comment]
Please assign it to me!

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Go ahead
