### ISSUE TITLE
Improving the design of accordian when open. 

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#269]
- The contrast on the Button of card is not good its hard to see on hover.

![Screenshot 2022-08-19 194656](https://user-images.githubusercontent.com/97726887/185639253-91809751-9ce8-4ddd-9be6-8abb13d6a334.png)

- Fixing the look of the links in Footer.

![Screenshot 2022-08-19 194610](https://user-images.githubusercontent.com/97726887/185639293-1857354e-2d53-41d1-b8aa-925b75277afe.png)

- Improving the inconsistency in the accordian 
  1. The first letter in some section is not capital.
  2. Also we can improve the text font , text color and bg color when accordian is open.

![Screenshot 2022-08-19 194632](https://user-images.githubusercontent.com/97726887/185639345-ebc85d52-8a6e-4822-ba24-dd2ba322b94f.png)

**Comment by ShivanshAr97** [comment]
Well the issue in the footer, it was because of someone who made a wrong PR raise or something I am not sure.

**Comment by ShivanshAr97** [comment]
But I have corrected it again in the PR #272

**Comment by ShivanshAr97** [comment]
As well as the scroll bar Someone maybe did it wrong

**Comment by ShivanshAr97** [comment]
> But I have corrected it again in the PR #272

You can see it in deploy log if you wish I have corrected both of them

**Comment by myhacktech** [comment]
@SahilDahekar make sure ur work are different from others to avoid clashes

**Comment by SahilDahekar** [comment]
> @SahilDahekar make sure ur work are different from others to avoid clashes

well i'll find different issues
i'll put a comment here before working on it

**Comment by SahilDahekar** [comment]
The accordian issue is different i'll work on it
