### ISSUE TITLE
Issue with how the PR are merged 

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#270]
- My PR of Improving the responsiveness of the Home page was merged here is the link.
https://github.com/Susmita-Dey/Sukoon/pull/208

- Now i dont know how the PR are merged but the current home page is not at all responsive.
- Maybe because after my PR was merged some else's PR had the older home page and it overrided mine.
- Have any idea how should we deal with this ? , i  have the branch whos PR was merged.

**Comment by myhacktech** [comment]
create another issue ,and then raise PR 
 @Susmita-Dey what 's ur views on this?

**Comment by SahilDahekar** [comment]
@myhacktech So should i create a issue and make a PR again??

**Comment by Susmita-Dey** [comment]
@myhacktech @SahilDahekar I guess it's overriden by some other PR.

**Comment by Susmita-Dey** [comment]
@SahilDahekar just push the code by creating another PR and mention that this was the issue as it will be a duplicate PR and also  no extra points will be given as I've allotted points for your previous PR and now you're going to push the same code.
