### ISSUE TITLE
Improving button UI in yoga page [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#273]
I would like to improve the interface of this button

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/185644582-56e68e48-08bd-479c-999e-d36fcaf68d0d.png)

**Comment by popcandy1x** [comment]
Bro I have already raised this issue:https://github.com/Susmita-Dey/Sukoon/issues/267
