### ISSUE TITLE
Improving the yoga section [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#274]
I would like to improve the upper region of yoga section so as to improve the readability of the text

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/185646123-741a0f37-2e03-416d-be4e-96271923b49a.png)

**Comment by popcandy1x** [comment]
Bro I have already raised this issue:https://github.com/Susmita-Dey/Sukoon/issues/267

**Comment by popcandy1x** [comment]
Bro I have already raised this issue:https://github.com/Susmita-Dey/Sukoon/issues/267

**Comment by ShivanshAr97** [comment]
okay
