### ISSUE TITLE
Adding the custom scroll bar in all the pages [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#275]
I would like to add the scroll bar which was created by me in all the pages

**Comment by AnshuPathak-88825** [comment]
Bro I've already made PR
PR #230

**Comment by ShivanshAr97** [comment]
Bro
I think scroll BAR and SMOOTH scroll feature is different🙂

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Do you mean your changes have been deleted or you want to add the changes?

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 Do you mean your changes have been deleted or you want to add the changes?

In the previous PR, it was added in the Home page only
Now, I would like to add them in all the other pages as well

**Comment by ShivanshAr97** [comment]
> > Bro I've already made PR PR #230
> 
> I think scroll BAR and SMOOTH scroll feature is different🙂

@Susmita-Dey see this

**Comment by Susmita-Dey** [comment]
What exactly @ShivanshAr97 wanna add?

**Comment by Susmita-Dey** [comment]
What exactly @ShivanshAr97 wanna add?

**Comment by ShivanshAr97** [comment]
A scroll bar same as PR #257 but in all the pages

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Wait for some days, if @AnshuPathak-88825 PR gets merged then it will be an duplicate issue
