### ISSUE TITLE
Fixing the UI of footer

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#276]
![Screenshot (330)](https://user-images.githubusercontent.com/94471189/185658974-aa435ef3-0781-45c7-81a2-1e67c5292723.png)

**Comment by ShivanshAr97** [comment]
been taken care of 👍
See deploy log of PR #272

**Comment by Vanshiii203** [comment]
> been taken care of 👍 See deploy preview of PR #272

Okay!!
