### ISSUE TITLE
Fix : Home Page ( About Us) Images

### ISSUE THREAD

**Issue by IAmTamal** [Susmita-Dey/Sukoon#277]
## Home Page (About Us)

 - The Members has images, which looks `streched out` and can be fixed with some minor fixes.

## Take a look at the streched out images 

![image](https://user-images.githubusercontent.com/72851613/185677578-172cd0c2-b01b-4584-83a8-6de7d25d25e9.png)

I would like to work on this !

**Comment by Susmita-Dey** [comment]
Hey @IAmTamal This is what I wanted to have actually. But are you an SSoC contributor?

**Comment by IAmTamal** [comment]
Oops, i thought the repo was Open for all  ! 
No , i am not an SSoC contributor !

**Comment by Susmita-Dey** [comment]
@IAmTamal It is open for all but currently it's under SSoC program for the next 2 months. Let me ask the team if I can assign others or not. If I can, then I will assign it to you.

**Comment by Susmita-Dey** [comment]
@IAmTamal Sorry I can't assign this to you currently. You can check my other projects for improvement.

**Comment by Susmita-Dey** [comment]
Waiting for SSoC contributors to take up.

**Comment by jainss** [comment]
Hello @Susmita-Dey  can i contribute in this issue i'm also a part of SSoC.

**Comment by Susmita-Dey** [comment]
@jainss Can you do it?

**Comment by jainss** [comment]
no i am not did it

**Comment by jainss** [comment]
actually i'm busy in the collage placement so there is time issue you assign this to anyone

**Comment by Susmita-Dey** [comment]
> actually i'm busy in the collage placement so there is time issue you assign this to anyone

Okay

**Comment by yvrjprshr** [comment]
Hey! I want to work on this issue.
Kindly assign me!

**Comment by Susmita-Dey** [comment]
@yvrjprshr I have removed Shayan Pal recently from my project.  So, what you can do is add a line like this: 
![image](https://user-images.githubusercontent.com/79099734/190866183-217ad015-358b-4f23-80fd-17893cfa396b.png)

Tell me if you can do it or not

**Comment by yvrjprshr** [comment]
Can you explain me in brief
what line do you want to be added ?
Where do you want it to be added ?

By the was this issue is about fixing images in about section which is not looking good due to streching. Isn't it ?

**Comment by Vanshiii203** [comment]
@Susmita-Dey Can I work on this??
I will also align the Let's connect button 
![Screenshot (396)](https://user-images.githubusercontent.com/94471189/190887796-8193985c-141f-4d41-a23d-d4c170bcae5c.png)
