### ISSUE TITLE
Adding a Carousel effect to the Testimonials section [SSOC]

### ISSUE THREAD

**Issue by vandana3869** [Susmita-Dey/Sukoon#278]
here is the demo
https://user-images.githubusercontent.com/84574563/185762499-77a55027-afea-4414-8b71-6574ce139cd5.mp4

**Comment by MridulTi** [comment]
Can you add a bit more information on the specifics of precisely the kind of result that you are looking forward to

**Comment by vandana3869** [comment]
> Can you add a bit more information on the specifics of precisely the kind of result that you are looking forward to

here is the preview of the result for reference
https://user-images.githubusercontent.com/84574563/185762499-77a55027-afea-4414-8b71-6574ce139cd5.mp4

**Comment by imaaquibali** [comment]
@vandana3869 Go for it!
