### ISSUE TITLE
Invisible buttons on Mobile view of Reading Therapy page

### ISSUE THREAD

**Issue by continualWolf** [Susmita-Dey/Sukoon#279]
![Invisible Buttons On Mobile](https://user-images.githubusercontent.com/77812385/185694702-1c3e22bf-426d-4127-95f1-2bc722b00e05.PNG)
On the Reading Therapy page, on the mobile view there are some invisible buttons(the buttons that say "read" under the book information).
This is my first time doing open source, so i would like to work on this :)

**Comment by Susmita-Dey** [comment]
@continualWolf Go ahead

**Comment by Susmita-Dey** [comment]
@continualWolf Are you in SSoC?

**Comment by continualWolf** [comment]
@Susmita-Dey  What is SSoc ?

**Comment by continualWolf** [comment]
Did not mean to close that haha

**Comment by continualWolf** [comment]
.
