### ISSUE TITLE
To improve UI (background and color scheme with text fonts in different color)

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#28]
I would like to make some changes to the UI of the audio therapy page its background and text are not visible clearly.
assign me this issue.

![Screenshot (210)](https://user-images.githubusercontent.com/87818185/182911139-248d2855-3f2d-4748-b74e-20b9d71dad55.png)

**Comment by Susmita-Dey** [comment]
Closing this now. We'll have a meeting and after that you can start contributing.

**Comment by Kirankp25** [comment]
ya ok
