### ISSUE TITLE
Improving the background and submit button

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#281]
I want to improve the submit button and also the background of this page.
![Uploading Screenshot (332).png…]()

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Screenshot has not been uploaded properly

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Screenshot has not been uploaded properly
![Screenshot (332)](https://user-images.githubusercontent.com/94471189/185735904-16bdd759-b952-4b1f-8474-f6e8b3654a0d.png)
