### ISSUE TITLE
SignUp Button

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#282]
I fixed the button and the PR was merged, Here is the link- https://github.com/Susmita-Dey/Sukoon/pull/240
The current deployed website doesn't have these changes. 
Should I raise a PR again?

**Comment by Susmita-Dey** [comment]
@Vanshiii203 We have 2 types of login signup html files. Someone needs to delte the old ones.

**Comment by Vanshiii203** [comment]
> @Vanshiii203 We have 2 types of login signup html files. Someone needs to delte the old ones.
I was talking about-
![Screenshot (333)](https://user-images.githubusercontent.com/94471189/185735968-fc185632-11e5-4bd4-8a95-c5d9fcf769a5.png)

For that login signup file, I have linked the new file in my previous PR which is currently not merged

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Make the changes in that PR first and go with this. Also, after deleting the old files, rename the new ones as `login.html` and `signup.html`
