### ISSUE TITLE
In Yoga Therapy Section, Image looks too stretched & can add bullets to the points

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#283]
The image SVG below Benefits of Yoga looks too stretched and the benefit's readability can be increased by using any bullet.
Can I work on this issue?
![image](https://user-images.githubusercontent.com/89779447/185732477-8982c11e-e9d4-44c6-8888-3b4f4dd0d68e.png)

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Go ahead
