### ISSUE TITLE
Fix home page footer

### ISSUE THREAD

**Issue by con-artist** [Susmita-Dey/Sukoon#285]
![image](https://user-images.githubusercontent.com/82517773/185740689-c17d9025-edb4-4268-bd65-dfd11d3a43fb.png)

The contact icons and the links are not styled properly
I will fix them and make it like the footers on the service pages

**Comment by myhacktech** [comment]
probably this issue is created already

**Comment by con-artist** [comment]
@myhacktech  are you sure ? I don't see any such issue

**Comment by myhacktech** [comment]
> @myhacktech are you sure ? I don't see any such issue

ok let me chk,i 'll assign if its not

**Comment by myhacktech** [comment]
> @myhacktech are you sure ? I don't see any such issue

yeah actually many tried to improve footer,but it is still not best,u can go with the issue

**Comment by vedsom** [comment]
@myhacktech if this issue pending can I solve it.

**Comment by con-artist** [comment]
I am working on it

**Comment by Susmita-Dey** [comment]
@con-artist Wait a PR is already there with footer.

**Comment by Susmita-Dey** [comment]
@myhacktech @con-artist Check #225 Closing this issue as duplicate
