### ISSUE TITLE
Laughing therapy page

### ISSUE THREAD

**Issue by con-artist** [Susmita-Dey/Sukoon#287]
![image](https://user-images.githubusercontent.com/82517773/185740832-de7330a4-b408-4c76-ab53-9c298b5a437c.png)
update the coming soon page with the laughing therapy page

**Comment by Vanshiii203** [comment]
@myhacktech @con-artist I am already working on this issue #44

**Comment by con-artist** [comment]
@Vanshiii203  Are you creating a laughing Therapy page?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Are you creating a laughing Therapy page?

Yes

**Comment by con-artist** [comment]
Well there is already a page created by someone. I am just linking it to the home page. You can create the new page and replace it with the old one

**Comment by myhacktech** [comment]
> Well there is already a page created by someone. I am just linking it to the home page. You can create the new page and replace it with the old one
yeah that page is still not created and it will be done by @Vanshiii203 ,u @con-artist should look for some other ways of improving it,or close the issue,till then i am unassigning it
