### ISSUE TITLE
improve the navigation bar UI.

### ISSUE THREAD

**Issue by Kritika0035** [Susmita-Dey/Sukoon#289]
the element needs to be aligned and a proper between them is to be made. also fixing the navigation bar is to be done.

**Comment by Kritika0035** [comment]
May I work on this issue then?

**Comment by myhacktech** [comment]
@Kritika0035 attach screenshot or link to explain

**Comment by Kritika0035** [comment]
![Screenshot (196)](https://user-images.githubusercontent.com/92821377/185752968-de3c2352-de3d-4244-951e-6865761cfba7.png)

also need to change the hover to maintain the hierarchy of the design.

**Comment by Susmita-Dey** [comment]
@Kritika0035 Make it like this:
![image](https://user-images.githubusercontent.com/79099734/186637187-988cb219-960b-45d7-bfe2-b8d80e037327.png)

**Comment by Kritika0035** [comment]
Okay maa'm... plz assign me this issue.

**Comment by Susmita-Dey** [comment]
> Okay maa'm... plz assign me this issue.

Go ahead

**Comment by Kritika0035** [comment]
I am a ssoc participant
