### ISSUE TITLE
Fix the position of the nav bar elements on home page

### ISSUE THREAD

**Issue by popcandy1x** [Susmita-Dey/Sukoon#291]
The nav bar elements look inappropriate at the center of the page so it would be better to shift them to the right of the page.
Original:-
![Screenshot 2022-08-20 at 9 48 14 PM](https://user-images.githubusercontent.com/81379049/185756607-e1f8ab71-af49-427c-8253-ab50453b4aad.png)
After Changes:-
![Screenshot 2022-08-20 at 9 48 21 PM](https://user-images.githubusercontent.com/81379049/185756616-e32781fc-0038-438f-bc4b-0cd857199fbd.png)

**Comment by Susmita-Dey** [comment]
Looks better. Go ahead @popcandy1x

**Comment by Susmita-Dey** [comment]
@popcandy1x Closing this as duplicate issue. Check #289

**Comment by popcandy1x** [comment]
> @popcandy1x Closing this as duplicate issue. Check #289

Ok👍
