### ISSUE TITLE
Changing the background Image of Yoga Therapy

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#294]
![Screenshot (334)](https://user-images.githubusercontent.com/94471189/185786976-a98c0b31-b662-474d-a356-11e0ca874dc4.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 The background image itself looks good to me. 
Have you found something more beautiful than this one? :thinking:

**Comment by keerthana054** [comment]
> @Vanshiii203 The background image itself looks good to me. Have you found something more beautiful than this one? 🤔

Can I change the font on this page? Enhancing it

**Comment by Vanshiii203** [comment]
> @Vanshiii203 The background image itself looks good to me. Have you found something more beautiful than this one? 🤔

![Screenshot (344)](https://user-images.githubusercontent.com/94471189/186920898-72633d4e-841b-4b76-ba87-8cc39f344e19.png)


![Screenshot (345)](https://user-images.githubusercontent.com/94471189/186920947-2bf65e7d-ac74-460f-ac13-1816820904de.png)

**Comment by Susmita-Dey** [comment]
@keerthana054 You can create a new issue for that.

**Comment by Susmita-Dey** [comment]
@Vanshiii203 The image is in portrait. Will it look good? I guess it would be stretched. Try once to check it.

**Comment by keerthana054** [comment]
> @keerthana054 You can create a new issue for that.

Okay :)

**Comment by Vanshiii203** [comment]
> @Vanshiii203 The image is in portrait. Will it look good? I guess it would be stretched. Try once to check it.


https://user-images.githubusercontent.com/94471189/187022708-3738b7c4-9095-4386-bebf-a23fff0ea616.mp4

**Comment by myhacktech** [comment]
updates @Vanshiii203
