### ISSUE TITLE
UI of Yoga Therapy page

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#299]
To maintain the similarity, I would like to improve the UI of the Yoga Therapy page by making it similar to the other pages.

![Screenshot (336)](https://user-images.githubusercontent.com/94471189/185844548-19bc9606-f983-4bf3-814b-611908eed0f0.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Show me the UI after having a sketch in Figma or Canva or whatever you prefer. I don't want to reject your PR later on if it doen't look good.

**Comment by MridulTi** [comment]
Is this issue still in progress or should I showcase the design I have in mind for the page?

**Comment by Susmita-Dey** [comment]
@MridulTi Wait for some more days to get assigned. I'll assign you if @Vanshiii203 fails to comment here within the next 10 days

**Comment by MridulTi** [comment]
sure

**Comment by myhacktech** [comment]
are u interested to work on this @MridulTi ,reply or i will have to close issue

**Comment by MridulTi** [comment]
> are u interested to work on this @MridulTi ,reply or i will have to close issue

I am Interested in working on it but I would need some time for it as it is a whole page I have to work on
