### ISSUE TITLE
add text next to logo

### ISSUE THREAD

**Issue by mohammedavez125** [Susmita-Dey/Sukoon#3]
A brand name next to logo is missing , makking it look empty

**Comment by Hirdey-1999** [comment]
I Did This Check The Results in The Image

![image](https://user-images.githubusercontent.com/71271612/169456099-881bc3c0-ba32-40a3-93a8-20ad448b9ceb.png)

**Comment by Susmita-Dey** [comment]
> I Did This Check The Results in The Image
> 
> ![image](https://user-images.githubusercontent.com/71271612/169456099-881bc3c0-ba32-40a3-93a8-20ad448b9ceb.png)

Looks awesome. I'm assigning it to you. Kindly create a PR.

**Comment by mohammedavez125** [comment]
looks great , I'll try to change explore button in container making it more
attractive

**Comment by Hirdey-1999** [comment]
Actually it is my first time can you help

**Comment by Susmita-Dey** [comment]
> Actually it is my first time can you help

Yes, sure. Where are you stuck?

**Comment by Susmita-Dey** [comment]
@mohammedavez125 KIndly create a separate issue for that to get assigned and describe briefly what changes you wanna make.

**Comment by Hirdey-1999** [comment]
> > Actually it is my first time can you help
> 
> Yes, sure. Where are you stuck?

Creating The PR

**Comment by Susmita-Dey** [comment]
> Creating The PR

Ok

**Comment by Hirdey-1999** [comment]
Please Merge The Pull Request It Has Changes With Logo And The Name Of The Website
