### ISSUE TITLE
reading therapy page

### ISSUE THREAD

**Issue by rani620** [Susmita-Dey/Sukoon#300]
want to change the reading therapy  page  ui and hover effect

**Comment by myhacktech** [comment]
attach screenshot for better explanation
@rani620

**Comment by Susmita-Dey** [comment]
@myhacktech Don't assign like this without ss otherwise later on when their PRs won't be merged, it will hurt them.

**Comment by Susmita-Dey** [comment]
@rani620 Can you add screenshots of your changes?

**Comment by rani620** [comment]
> @myhacktech Don't assign like this without ss otherwise later on when their PRs won't be merged, it will hurt them.

maam if u assigned this issue to me afterthat i will have to work upon on it ..

**Comment by rani620** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/96174308/187038108-aa4a26bf-1ba2-4766-b113-9c83187c2367.png)

**Comment by myhacktech** [comment]
> > @myhacktech Don't assign like this without ss otherwise later on when their PRs won't be merged, it will hurt them.
> 
> maam if u assigned this issue to me afterthat i will have to work upon on it ..

yes

**Comment by rani620** [comment]
i did the pr plz close this  issue
