### ISSUE TITLE
want to add some property to contact section

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/Sukoon#301]
![image](https://user-images.githubusercontent.com/78332454/185885497-801aec43-8ae9-4c10-ad94-bbbdd32de215.png)

there's underline ,bullents and not proper color I want to make some chanes regarding it

**Comment by AnshuPathak-88825** [comment]
pls assgin me this issue

**Comment by Susmita-Dey** [comment]
Duplicate issue. Check #225 A PR is already creted.
