### ISSUE TITLE
want to change about section 

### ISSUE THREAD

**Issue by rani620** [Susmita-Dey/Sukoon#304]
will give some transition ,want to 
![Screenshot (22)](https://user-images.githubusercontent.com/96174308/185922894-53046252-b34b-4c8c-a67e-bda8ca5e88a8.png)
 change some layout and color and want to add some hover effect.

**Comment by imaaquibali** [comment]
@rani620 assigned

**Comment by rani620** [comment]
I am a SSOC participant.
