### ISSUE TITLE
Converting the website into PWA [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#312]
I would like to convert the website into a Progressive Web Application so that it can be installed in the user device or added to home screen and can also function offline. 

(For SSOC contribution)

**Comment by ShivanshAr97** [comment]
Please assign it to me

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Nice idea. Share some resources in discord via dm. I also wanna learn how to add this feature to websites.

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 Nice idea. Share some resources in discord via dm. I also wanna learn how to add this feature to websites.

Ok 🙂
