### ISSUE TITLE
Adding a custom scrollbar [SSOC]

### ISSUE THREAD

**Issue by Yash-RajSingh** [Susmita-Dey/Sukoon#316]
The website currently has the default scrollbar. The default scrollbar is contrasting to the color if the website, so I'd like to add a colored custom scrollbar. Kindly please assign this issue to me.

![image](https://user-images.githubusercontent.com/85413348/186432363-81a2c014-a854-4418-afc7-acd38207afa7.png)

**Comment by Susmita-Dey** [comment]
@Yash-RajSingh Go here:- https://sukoon-stress-free.netlify.app/ 
Custom scrollbar is already there. Duplicate issue again. Closing this.
