### ISSUE TITLE
Minor fixes in the footer [SSOC]

### ISSUE THREAD

**Issue by Yash-RajSingh** [Susmita-Dey/Sukoon#317]
The elements of the footer currently have contrasting colors because of the links. Also, the bullets of the list items are still visible. I'd like to fix these minor ui problems. Kindly please assign this issue to me.

![image](https://user-images.githubusercontent.com/85413348/186433269-ac519b38-33e4-4f2e-9b83-1fe7e34c6e0d.png)

**Comment by Susmita-Dey** [comment]
@Yash-RajSingh Check #225 PR is already created.
