### ISSUE TITLE
Improving UI of the members card [SSOC]

### ISSUE THREAD

**Issue by Yash-RajSingh** [Susmita-Dey/Sukoon#319]
Currently the member cards just have a basic dark blue background. I'd like to add glassmorphism effect and improve the UI a bit. Please assign this issue to me.
![image](https://user-images.githubusercontent.com/85413348/186624259-64878c08-d8e9-4272-a5af-4710bf4ac940.png)

**Comment by Susmita-Dey** [comment]
@Yash-RajSingh Create an UI in canva or figma or somewhere else you like and show me first.

**Comment by Susmita-Dey** [comment]
@Yash-RajSingh Any updates?

**Comment by Yash-RajSingh** [comment]
> @Yash-RajSingh Any updates?

Hey, I'm sorry I forgot to raise a PR since I got busy with my internship. Since I don't know how to use Figma or canva, I've implemented the changes so that you can see the changes yourself

**Comment by Susmita-Dey** [comment]
@Yash-RajSingh Yes checking.
