### ISSUE TITLE
[TYPO] - FAQ Section

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#321]
![image](https://user-images.githubusercontent.com/79099734/186643605-481b1203-b35b-46a5-a6f6-f6271587c346.png)

Change the **w** to **W** in this section.

**Comment by 29Aastha** [comment]
pls assign me this issue .. i m an ssoc participant

**Comment by Susmita-Dey** [comment]
@29Aastha Go ahead
