### ISSUE TITLE
Change the font family of "Let's Connect" Button on Meet our member section.

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#331]
Let's Connect font style doesn't seem good, so can I change it with a new font under SSOC'22?

![image](https://user-images.githubusercontent.com/89779447/186948614-5362132d-136c-461d-bd80-88d7a607cffd.png)

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Go ahead
