### ISSUE TITLE
Added a blur filter in the background of the Home page navbar.

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#333]
- The navbar on the home page has no background hence it clashes with other elements.
- We should add a blur filter so that we can distinguish the content and navbar.

<img width="946" alt="Screenshot 2022-08-27 111019" src="https://user-images.githubusercontent.com/97726887/187016613-99069567-131c-440a-925e-74e6a5a090cd.png">
<img width="944" alt="Screenshot 2022-08-27 111000" src="https://user-images.githubusercontent.com/97726887/187016617-5cc3164f-efda-4e40-887b-895c0958a542.png">

**Comment by SahilDahekar** [comment]
I want to work on this issue

**Comment by Susmita-Dey** [comment]
@SahilDahekar Go ahead
