### ISSUE TITLE
Fix the "X" sign on Talking Therapy page

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#336]
I wanted to change the Navbar design from a normal design to a Glass-morphism effect. Can I do this under SSOC'22?
Before - 
![image](https://user-images.githubusercontent.com/89779447/187023159-c806aa15-7dde-43e8-883a-c8da5fcc2aa8.png)

After ( Want to make it like this ) - 
![Screenshot 2022-08-27 142418](https://user-images.githubusercontent.com/89779447/187023172-fd77799b-ed7c-4bdb-a8fe-a9dabd92732f.png)

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Wait for a while. Someone has made drastic changes to the website.

**Comment by MohitNamdev22** [comment]
@Susmita-Dey No issues Ma'am!

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Can you fix the "x" in talking therapy?
Just go to the original site, you'll get what I'm asking you to do

![image](https://user-images.githubusercontent.com/79099734/189569987-9d6e0ebf-ac9a-40b0-aee6-52d47e344891.png)

**Comment by MohitNamdev22** [comment]
Yes @Susmita-Dey I can work on it 👍

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Change the issue title and go ahead
