### ISSUE TITLE
The therapy pages are broken 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#337]
@Susmita-Dey 
The laughing therapy page is not visible( PR #293 ), the talking therapy page is broken and also the responsiveness of the navbar of reading therapy is gone, I made it responsive in my last PR #325 

![Screenshot (353)](https://user-images.githubusercontent.com/94471189/187023831-bc2fcf71-2734-484f-8318-8f484baad41d.png)

![Screenshot (354)](https://user-images.githubusercontent.com/94471189/187023884-718d740e-2c29-4b7a-b49c-b277d4757128.png)

![Screenshot (355)](https://user-images.githubusercontent.com/94471189/187024155-faf81402-e7ca-487c-a4e4-e9c912c9007e.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Let me check

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Let me check

Please check #302 as well

**Comment by Vanshiii203** [comment]
@Susmita-Dey 
Should I fix the issues??

**Comment by Susmita-Dey** [comment]
Yeah do it

**Comment by SahilDahekar** [comment]
hey @Susmita-Dey @myhacktech  some of the issue in mentioned by @Vanshiii203 are already taken like fixing the navbar on home page is this issue #333

**Comment by Vanshiii203** [comment]
> hey @Susmita-Dey @myhacktech some of the issue in mentioned by @Vanshiii203 are already taken like fixing the navbar on home page is this issue #333

I have fixed the therapy pages. You can fix the navbar of home page.
