### ISSUE TITLE
Fixing the Audio thereapy page

### ISSUE THREAD

**Issue by Eknoor02** [Susmita-Dey/Sukoon#346]
Cross sign is appearing at the top-right corner of the Audio thereapy page.
SSOC 2022

**Comment by myhacktech** [comment]
attach screenshot for explanation

**Comment by SahilDahekar** [comment]
i opened the same issue 2 days ago check this out #339

**Comment by myhacktech** [comment]
> @Eknoor02 @myhacktech i opened the same issue 2 days ago check this out #339

ok
