### ISSUE TITLE
Make the mail in other therapy pages to Hyperlink

### ISSUE THREAD

**Issue by Surya8991** [Susmita-Dey/Sukoon#348]
SSOC 2022 Participant
Converting the mail in footer section from other pages to same as home . So we can send mail by clicking on it.
![image](https://user-images.githubusercontent.com/85568108/187120965-f3f17250-f890-4b2a-abc6-c9dbcdd341dd.png)
![image](https://user-images.githubusercontent.com/85568108/187120972-54673fd3-c0c9-4546-aa01-e68b958b8ed1.png)

**Comment by Vanshiii203** [comment]
@Surya8991 @myhacktech Resolved this in #372.
