### ISSUE TITLE
Working on navbar and About section

### ISSUE THREAD

**Issue by YasirObaibullah99** [Susmita-Dey/Sukoon#35]
I want to change the navbar and give shadow effect in About section 
And I am in SSOC also

**Comment by Susmita-Dey** [comment]
@YasirObaibullah99 Go ahead

**Comment by YasirObaibullah99** [comment]
Sure

**Comment by SachinMittal1766** [comment]
@YasirObaibullah99 Updates? It is more than 3 days

**Comment by YasirObaibullah99** [comment]
@SachinMittal1766  Its already merge

**Comment by YasirObaibullah99** [comment]
![Screenshot from 2022-08-08 08-54-22](https://user-images.githubusercontent.com/83706868/183332231-5761572c-7b08-4cc0-8dd4-84af1c4a3510.png)
