### ISSUE TITLE
UI Fix needed in Reading Section

### ISSUE THREAD

**Issue by Anubhavgupta14** [Susmita-Dey/Sukoon#353]
UI Fix needed in Reading Section
![hyper](https://user-images.githubusercontent.com/97956667/187253416-18e1f13f-3703-4e8f-91d0-dc6956381ad4.jpg)

**Comment by Vanshiii203** [comment]
@myhacktech @Anubhavgupta14 
This issue is already been resolved.PR #341

**Comment by myhacktech** [comment]
@Anubhavgupta14 highlight on screenshot u want to work upon ,as something similar is already created by other participant
