### ISSUE TITLE
UI Improvement needed in Sign-Up page

### ISSUE THREAD

**Issue by Anubhavgupta14** [Susmita-Dey/Sukoon#354]
UI Improvement needed in Sign-Up page. @Susmita-Dey @vaibhavsharma1234 Please Assign it to me.

**Comment by myhacktech** [comment]
better if u attach screenshot @Anubhavgupta14

**Comment by Anubhavgupta14** [comment]
![sukoon sign](https://user-images.githubusercontent.com/97956667/189066189-ab0ee5bc-9479-4b8b-8093-fac20d4d19e6.jpg)
I will add the Navbar, Add Animated Background.

**Comment by Anubhavgupta14** [comment]
@myhacktech Please Assign it to me.
