### ISSUE TITLE
Service Section

### ISSUE THREAD

**Issue by AliReza1083** [Susmita-Dey/Sukoon#356]
I fixed this issue but RN it is same like the last time.

![image](https://user-images.githubusercontent.com/99729607/187832510-83e9c3da-73b3-442e-843c-9a1d23b3a2fc.png)

**Comment by imaaquibali** [comment]
@AliReza1083 did your PR merged?

**Comment by AliReza1083** [comment]
Yup, it was merged and we could see the changes inside the website but right now it is like the last one hh

**Comment by Susmita-Dey** [comment]
@AliReza1083 Check #352 The issue will be fixed soon. Closing this as duplicate.
