### ISSUE TITLE
Add a Carousel in the Meet our Member section

### ISSUE THREAD

**Issue by Osman-Rasooli** [Susmita-Dey/Sukoon#357]
- It would be better to add a carousel-slider in the _**About Us**, **Meet our Members**_ section.
- The profile images in the _**About us**_ section are also stretched up, so using object-fit would be a great step.

**Comment by myhacktech** [comment]
attach sample,or ur work should be up to the mark,,then i will assign to u

**Comment by Susmita-Dey** [comment]
@Osman-Rasooli Are you a Social Summer of Code participant?

**Comment by Osman-Rasooli** [comment]
Not actually, I was involved in family business for a while, so I had to
skip programming for a while. Now, I'm back to development.

**Comment by Susmita-Dey** [comment]
@Osman-Rasooli Since you're a not an SSoC participant, I can't assign it to you now as this project under SSoC
