### ISSUE TITLE
Adding a color to Navbar 

### ISSUE THREAD

**Issue by Vignesh2131** [Susmita-Dey/Sukoon#358]
When the page is getting scrolled as the navbar is sticky, it is fixed, but the navbar's visibility is getting low while getting to the testimonial section.
So I want to add color to the navbar. So that navbar will be visible 
![image](https://user-images.githubusercontent.com/96634914/188157630-970e7440-0650-499b-b136-f9bfb08b30f2.png)

**Comment by SahilDahekar** [comment]
@myhacktech  @Vignesh2131 this issue is already fixed with a pull request also being made #333
