### ISSUE TITLE
Making the footer on therapy pages similar to home page.

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#359]
1. On DIfferent Therapy pages the footer looks different.

- Home Page Footer.
<img width="943" alt="Screenshot 2022-09-03 131733" src="https://user-images.githubusercontent.com/97726887/188261504-3dd4b7ce-50cb-42cc-8c20-2d02093e7d1a.png">

- Audio Therapy Page Footer.
<img width="939" alt="Screenshot 2022-09-03 131805" src="https://user-images.githubusercontent.com/97726887/188261502-6f01c6a7-57fe-4f22-a623-68e53e3f6b53.png">

- Yoga Therapy Page Footer.
<img width="944" alt="Screenshot 2022-09-03 131834" src="https://user-images.githubusercontent.com/97726887/188261500-d8c84a2d-ee68-4a4b-9393-c3eb5d81771f.png">

- Reading Therapy Page Footer.
<img width="946" alt="Screenshot 2022-09-03 131901" src="https://user-images.githubusercontent.com/97726887/188261498-34c56ab4-8e49-49a8-a726-d707294a35f0.png">

- Talking Therapy Page Footer.
<img width="947" alt="Screenshot 2022-09-03 131930" src="https://user-images.githubusercontent.com/97726887/188261495-a4b30b22-cbb3-4097-b011-ccce3f504bfa.png">

- Here are Three solutions for this
  1. Make them look similar on all pages.
  2. Remove them from Therapy pages as it is not of importance there and a person can navigate back to home page just with the home link in navbar.
  3. Create a new design for footer on Therapy Pages.

**Comment by SahilDahekar** [comment]
I want to work on this issue

**Comment by Vanshiii203** [comment]
@SahilDahekar this issue is already assigned to me #344

**Comment by SahilDahekar** [comment]
okay i will close this issue
