### ISSUE TITLE
Improving the design of the mobile layout navbar menu on home page

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#361]
- Want to change the background color on the home page menu.
- Want to improve the hover effect on the links in menu and also change the slide in animation.
- Also i want to create a svg toggling function between hamburger menu and close svg for the menu toggle.
- I think we can remove the home link in navbar on home page its senseless.

- This is how the menu looks and also the hamburger is too big.
<img width="362" alt="Screenshot 2022-09-03 141330" src="https://user-images.githubusercontent.com/97726887/188263220-35e53011-a23d-4c05-aed8-a0135df343bb.png">

- The links in menu on hover dosent look good.
<img width="362" alt="Screenshot 2022-09-03 141358" src="https://user-images.githubusercontent.com/97726887/188263227-dfca1d61-2ad5-4865-a7cb-96b31e1e3070.png">

**Comment by SahilDahekar** [comment]
I want to work on this issue plz assign it to me

**Comment by AliReza1083** [comment]
It will be amazing.
Wish you all the best.
