### ISSUE TITLE
Improving the Responsiveness of the Yoga Therapy Page And Enhancing the design.

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#367]
- Want to Improve the design of the yoga therapy page.
- Want to Improve the responsiveness of the yoga Therapy page.

What i will be improving : 
- Will change the Theme of yoga therapy to this https://coolors.co/palette/ffffff-00171f-003459-007ea7-00a8e8.
- Will be changing the youtube video size on mobile layout.
<img width="307" alt="Screenshot 2022-09-07 210108" src="https://user-images.githubusercontent.com/97726887/188919410-bc0970ee-56fc-458b-a391-2c3be4dccac6.png">
<img width="311" alt="Screenshot 2022-09-07 205948" src="https://user-images.githubusercontent.com/97726887/188919424-fcfc4e37-e21d-4ca7-8c7d-affbbedf60a1.png">
- Will be Changing the background of the image in header
- Will be Changing the hamburger menu to toogle with "X" on open.

**Comment by SahilDahekar** [comment]
I want to work on this issue

**Comment by Susmita-Dey** [comment]
@SahilDahekar Show me the UI color changes after you're done. Go ahead

**Comment by SahilDahekar** [comment]
yep

**Comment by Anubhavgupta14** [comment]
@SahilDahekar  I want to work for this issue, as it is open since last 13 days. If you allow.
