### ISSUE TITLE
Working on the Contact us form 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#37]

**Comment by Atharv-110** [comment]
Elaborate the issue, then it will be assigned to you.
Provide description.

**Comment by Vanshiii203** [comment]
I would like to improve the UI of the form.

**Comment by Atharv-110** [comment]
Refer #40 issue for how the description is drafted!

**Comment by Vanshiii203** [comment]
I would like to add a placeholder to  the message box, add animation to the button and a hover effect to the go back option. Also, I would like to do  some basic padding and margin changes .

**Comment by Atharv-110** [comment]
Go ahead @Vanshiii203.
Assigned to you.
All the best.

**Comment by Vanshiii203** [comment]
Thanks!
