### ISSUE TITLE
Properly design the navbar of landing page, so that it won't overlap with background content

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#371]
The navbar of landing page is overlapping with the background content. So, can I work on it and fix it? Under SSOC'22
![image](https://user-images.githubusercontent.com/89779447/189141118-c3345c78-8ed7-42f9-8c93-816e27819a7d.png)

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Check #352 This thing will be fixed soon. Closing this as duplicate
