### ISSUE TITLE
Adding list style to the content in yoga therapy 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#375]
Adding list style to the content-
![Screenshot (376)](https://user-images.githubusercontent.com/94471189/189479861-663f5008-5ed5-466d-9606-c8d16ae12760.png)

**Comment by Susmita-Dey** [comment]
It was fixed by @MohitNamdev22 earlier I guess.

**Comment by MohitNamdev22** [comment]
Yes I had worked on it and then after some time there was some issue on the page, due to which it's not visible I guess 🤔

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Can you do it again?

**Comment by MohitNamdev22** [comment]
> 

Okay @Susmita-Dey

**Comment by Susmita-Dey** [comment]
> Okay @Susmita-Dey

Closing this as of duplicate PR. When you'll pushing the same code, kindly write it as duplicate one.
