### ISSUE TITLE
Improving the navbar of laughing therapy 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#376]
I want to improve the  navbar of laughing therapy page  and make it similar to other pages
On keeping the menu open and making the window full screen we can still see the mobile layout menu.
![Screenshot (377)](https://user-images.githubusercontent.com/94471189/189480398-938c4a1e-57b0-4476-814b-504c204c5601.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Go ahead
