### ISSUE TITLE
Improving the Landing page UI and Font Family

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#38]

**Comment by siddhi-244** [comment]
Please describe the issue more

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Check #35 What extra you wanna add?

**Comment by MohitNamdev22** [comment]
I'll improve the font family of landing page text / headings give them proper visuality. And wanna add a glass morphism effect to NavBar.

**Comment by MohitNamdev22** [comment]
If someone is already assigned to Navbar, you may assign me Landing Page issue...

**Comment by siddhi-244** [comment]
> If someone is already assigned to Navbar, you may assign me Landing Page issue...

Navbar issue is already been assigned to someone else. Landing page font issue can be done by you !

**Comment by MohitNamdev22** [comment]
Thanks! Yeah I'll work on Landing Page
