### ISSUE TITLE
Changing the background of navbar of home page 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#380]
from->
![Screenshot (382)](https://user-images.githubusercontent.com/94471189/189515848-288b1db0-79e0-419e-ae1b-ed9bb2993021.png)

To->
![Screenshot (380)](https://user-images.githubusercontent.com/94471189/189515860-ae30ea58-3064-413a-a598-9f89025358d9.png)

**Comment by Susmita-Dey** [comment]
@imaaquibali @siddhi-244 @myhacktech What do you think about this?

**Comment by myhacktech** [comment]
> @imaaquibali @siddhi-244 @myhacktech What do you think about this?

it is quite difficult to select out of both.... @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@myhacktech Yes, that's why I'm confused whether or not to assign her

**Comment by Vanshiii203** [comment]
@Susmita-Dey Should I work on this?

**Comment by ShravaniAK** [comment]
can i work on this ?

**Comment by Susmita-Dey** [comment]
Closing this as not needed
