### ISSUE TITLE
Changing the font family in buttons in About us section

### ISSUE THREAD

**Issue by Vignesh2131** [Susmita-Dey/Sukoon#381]
The font inside the button "Let's connect" has no styling and go remained as sans serif

**Comment by Susmita-Dey** [comment]
@Vignesh2131 So, you wanna change the font style right?

**Comment by Vignesh2131** [comment]
Yeah I want to change the font syle. It is displaying the sans serif at moment. I want to make it to Poppins
![image](https://user-images.githubusercontent.com/96634914/189531139-a2ee1358-0fb8-498b-b8a8-a9aacdc0aef1.png)

**Comment by Susmita-Dey** [comment]
@Vignesh2131 Go ahead
