### ISSUE TITLE
[FEATURE] Adding a Spiritual Service

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#385]
Shall We add a Spiritual service or make a section under Yoga therapy?
What do you think?

**Comment by MohitNamdev22** [comment]
I think making a separate service section for spirituality will be better 🤔

**Comment by MohitNamdev22** [comment]
@Susmita-Dey can I work on this?

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Let's discuss this first in discord. I'll then assign it to you.

**Comment by MohitNamdev22** [comment]
Yeah, we can arrange a meet and first discuss it👍
And then I'll make a page prototype on Figma  before coding the page.

**Comment by Susmita-Dey** [comment]
> Yeah, we can arrange a meet and first discuss it+1 And then I'll make a page prototype on Figma before coding the page.

That's a good idea

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 Go ahead

**Comment by MohitNamdev22** [comment]
Sure @Susmita-Dey 👍

**Comment by MohitNamdev22** [comment]
@Susmita-Dey I have designed the website on Figma, please check the prototype & kindly give your suggestions

https://www.figma.com/file/4NbMFn3bG3cp8yClnPWwTg/Spirituality-Page---Sukoon?node-id=0%3A1

**Comment by MohitNamdev22** [comment]
@Susmita-Dey Can I again start working on it? Under Hacktoberfest 2022

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Can I again start working on it? Under Hacktoberfest 2022

Yeah, go ahead
