### ISSUE TITLE
[DOCUMENTATION] GitHub Contribution badge

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#389]
Add github contribution badges to display the contributors of te repository in **README** file.

**Comment by YasirObaibullah99** [comment]
I can add badges in the Readme file

**Comment by Susmita-Dey** [comment]
@YasirObaibullah99 Go ahead

**Comment by Susmita-Dey** [comment]
no, it's looking good

**Comment by YasirObaibullah99** [comment]
https://github.com/Susmita-Dey/Sukoon/pull/400 do review this one
