### ISSUE TITLE
Enhancing the Sukoon Logo and the Home page 

### ISSUE THREAD

**Issue by vandana3869** [Susmita-Dey/Sukoon#39]
Here is the improved design template https://sukoon.my.canva.site/    
I'm a SSoc Participant

**Comment by siddhi-244** [comment]
Lgtm

**Comment by SachinMittal1766** [comment]
@vandana3869 Updates?

**Comment by vandana3869** [comment]
Yeah...Right now I'm working on its responsiveness and the Carousel for services section

**Comment by SachinMittal1766** [comment]
@vandana3869 Make PR by tomorrow
