### ISSUE TITLE
There is something wrong with the images in audio therapy page.

### ISSUE THREAD

**Issue by yvrjprshr** [Susmita-Dey/Sukoon#391]

**Comment by yvrjprshr** [comment]
![Sukoon](https://user-images.githubusercontent.com/66880935/189595414-8f0eff2e-5341-4968-948b-336bb793b253.png)

**Comment by Susmita-Dey** [comment]
Closing this as spam because everything is working fine.

**Comment by yvrjprshr** [comment]
okay
