### ISSUE TITLE
fixing navbar of talking therapy page

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#397]
![Screenshot (388)](https://user-images.githubusercontent.com/94471189/189950772-b597bc4f-3ef5-4748-8cf7-ea7e0801b4dd.png)
![Screenshot (389)](https://user-images.githubusercontent.com/94471189/189950995-65e11815-8760-4bad-bf30-5e1962487994.png)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Go ahead

**Comment by Susmita-Dey** [comment]
@Vanshiii203 @MohitNamdev22 is working on removing the "x" part. Wait for him to create a PR first then you can create yours

**Comment by Vanshiii203** [comment]
> @Vanshiii203 @MohitNamdev22 is working on removing the "x" part. Wait for him to create a PR first then you can create yours

Okay
