### ISSUE TITLE
To improve UI

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#40]
I would like to contribute to your project by making some changes to the audio therapy page its background and text is not visible clearly so I won't change its color and fonts and also some essential changes, so assign me this task.

![Screenshot (210)](https://user-images.githubusercontent.com/87818185/183089883-7cea4205-af80-41d9-8928-48d086e9acf6.png)

**Comment by Atharv-110** [comment]
Nice @Kirankp25!
Go ahead, assigned to you!

**Comment by Kirankp25** [comment]
ya sure

**Comment by samvid2020** [comment]
hey, can I work on this issue?

**Comment by Atharv-110** [comment]
@samvid2020 this issue is already assigned, you can create another different issue.

**Comment by SachinMittal1766** [comment]
Updates @Kirankp25

**Comment by Susmita-Dey** [comment]
@Kirankp25 The audio therapy itself looks good and no changes as your mentioned are not needed now. closing this as no reply for a number if days.
