### ISSUE TITLE
making font family of all headings on home page similar

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#405]
making the font family of other headings similar to about us 

https://user-images.githubusercontent.com/94471189/190847960-d75d6414-e11d-45f6-a2c4-9b02dc37f2e5.mp4

**Comment by myhacktech** [comment]
#405

**Comment by myhacktech** [comment]
i think its ok,but still we expect PR to be better than present interface @Vanshiii203
