### ISSUE TITLE
Implementing a custom scroll bar on all pages.

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#407]
- Would like to improve a custom scroll bar on all the pages in the project.
- Also the scroll bar on home page need to be matched with the theme of the home page its not matching.

**Comment by SahilDahekar** [comment]
@Susmita-Dey @myhacktech plz assign me this issue.

**Comment by Susmita-Dey** [comment]
@SahilDahekar Go ahead

**Comment by ShivanshAr97** [comment]
@Susmita-Dey https://github.com/Susmita-Dey/Sukoon/issues/275 same issue was closed before as duplicate 😢
