### ISSUE TITLE
Improving the testimonial section 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#409]

**Comment by Susmita-Dey** [comment]
@Vanshiii203 What do you want to improve?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 What do you want to improve?
As discussed in yesterday's meeting, we can write the actual reviews of the contributors and add their images, and a carousel can be added, displaying 3 reviews in a single slide.
Something like this- 
![Screenshot_20220918-160240~2](https://user-images.githubusercontent.com/94471189/190897763-3f2c4057-081b-4509-a2a1-7a45c1fc0006.jpg)

**Comment by Susmita-Dey** [comment]
@Vanshiii203 First we have take reviews from others for that I think.

**Comment by Vanshiii203** [comment]
> @Vanshiii203 First we have take reviews from others for that I think.

Yes we can take that on discord and then I can add them to the website

**Comment by Susmita-Dey** [comment]
@Vanshiii203 I'm collecting data using the google form. I'll share it with you so that you can add them to the website.
