### ISSUE TITLE
i want to improve the services section its ui please assign it to me i am a ssoc participant

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Susmita-Dey/Sukoon#41]

**Comment by siddhi-244** [comment]
Describe the issue

**Comment by vaibhavsharma1234** [comment]
its very plain ui  i can add glassmorphism effect and make a ui little better by using eye pleasing colors 
currently it quite plan and average

**Comment by myhacktech** [comment]
@vaibhavsharma1234 issue of this type is already assigned

**Comment by Susmita-Dey** [comment]
@vaibhavsharma1234 Kindly find any bugs in the website or think of other enhancement or feature you can add/.make. Since it's a duplicate issue, I'm closing it.
