### ISSUE TITLE
Adding two more audio books to audio therapy 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#413]
-  https://www.audible.in/pd/The-Monk-Who-Sold-His-Ferrari-Audiobook/B072MR2L6V?qid=1663432045&sr=1-2&ref=a_search_c3_lProduct_1_2&pf_rd_p=2d02bc98-4366-4f94-99d9-5e898cda0766&pf_rd_r=PBF08GY7EPN53D1K48CC

- https://www.audible.in/pd/Good-Vibes-Good-Life-Audiobook/1788174992?qid=1663432525&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=2d02bc98-4366-4f94-99d9-5e898cda0766&pf_rd_r=PFHFS2XZPZE9CNS18WVB

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Go ahead
