### ISSUE TITLE
website responsive ness is lacking i would like to improve it kindly assign it to me i am a ssoc participant

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Susmita-Dey/Sukoon#42]

**Comment by Atharv-110** [comment]
@vaibhavsharma1234 please provide the description and attach some screenshot for the same.

**Comment by vaibhavsharma1234** [comment]
![p2](https://user-images.githubusercontent.com/96341386/183093404-15654e7e-fa03-4397-91a0-0a35a22daac1.png)
please refer to this sir
