### ISSUE TITLE
Let's Explore button position change 

### ISSUE THREAD

**Issue by Aniket1026** [Susmita-Dey/Sukoon#424]
### BUTTON POSITION
* Let's explore button on each card is not placed properly
* Placing the button towards bottom will make the user experience better

![Screenshot (110)](https://user-images.githubusercontent.com/92184189/191351973-e67065f0-6317-43db-b6b4-d5cffd701973.png)
 
As the screen size decreases the user experience becomes less and less attractive. As shown below

<img width="560" alt="Hacktoberfest 2022 issue" src="https://user-images.githubusercontent.com/92184189/191352246-bbb0304d-d1db-4d23-9ce7-63eb816ec009.png">

Regards,
Aniket

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.

**Comment by Susmita-Dey** [comment]
@Aniket1026 Are you an SSoC contributor?

**Comment by NageshMandal** [comment]
yes

**Comment by Aniket1026** [comment]
@Susmita-Dey I want to contribute in this for the hacktoberfest .

**Comment by ShravaniAK** [comment]
i want to work on this issue

**Comment by Susmita-Dey** [comment]
@Aniket1026 This project is not under hacktoberfest.

**Comment by ShravaniAK** [comment]
I will correct the button position and the all 3 look similar and more attractive

**Comment by rishabh3231** [comment]
please assign me this issue

**Comment by Aniket1026** [comment]
Thanks for assigning 😄
