### ISSUE TITLE
Need Some Enhancement In LogIn/SignUp Page

### ISSUE THREAD

**Issue by NageshMandal** [Susmita-Dey/Sukoon#426]
![21 09 2022_11 36 28_REC](https://user-images.githubusercontent.com/106006006/191428026-c12d1e5f-b68d-49b0-bd16-96b8534357c6.png)

**Comment by NageshMandal** [comment]
I want to work on this issue. Could you please assign it to me.

**Comment by Susmita-Dey** [comment]
@NageshMandal Are you an SSoC contributor?

**Comment by NageshMandal** [comment]
Yes I am a SSoC contributor
Want To Add Sukoon Logo In Login/Signup Section
Show/Hide Password In Login/Signup Section

**Comment by Susmita-Dey** [comment]
@NageshMandal Go ahead

**Comment by Vanshiii203** [comment]
@Susmita-Dey plz assign me this issue
