### ISSUE TITLE
To make its footer more effective

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#43]
I want to do some changes in the footer to make him more attractive by changing the background and text fonts colors etc.
so assign me this task. 

![footer](https://user-images.githubusercontent.com/87818185/183092548-df307ba5-d6b7-47f8-9573-87a11299c521.png)

**Comment by Atharv-110** [comment]
Go ahead @Kirankp25.
Assigned to you.

**Comment by Susmita-Dey** [comment]
@Kirankp25 any updates?

**Comment by Kirankp25** [comment]
yes, today I will make PR for it
