### ISSUE TITLE
Arrange 2 files

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#431]
Arrange these two files inside a folder named `docs`
![image](https://user-images.githubusercontent.com/79099734/191676987-ca2859f6-a841-4f8c-96f9-0853d6532be8.png)

Task to perform:
- Create a new folder called `docs`
- Cut the two files and paste into `docs`

**Comment by ShravaniAK** [comment]
i can work on this

**Comment by ShravaniAK** [comment]
please assign me

**Comment by Susmita-Dey** [comment]
@ShravaniAK Go ahead
