### ISSUE TITLE
Adding animation to Testimonial section

### ISSUE THREAD

**Issue by Akayush-17** [Susmita-Dey/Sukoon#436]
Making testimonial card more interactive with background shadow and animation effect when mouse placed on it

**Comment by myhacktech** [comment]
@Akayush-17 add image also,otherwise ur pr will not be considered

**Comment by Akayush-17** [comment]
> @Akayush-17 add image also,otherwise ur pr will not be considered

testimonials already has an image

**Comment by MohitNamdev22** [comment]
Can I work on this?
