### ISSUE TITLE
Working on laughing therapy

### ISSUE THREAD

**Issue by keerthana054** [Susmita-Dey/Sukoon#44]
I would like to give this new feature of laughing therapy, which leads to a new tab where we find therapies to get stress free- through laughter.

**Comment by myhacktech** [comment]
@keerthana054 that means you will add a new webpage,right..?

**Comment by keerthana054** [comment]
> @keerthana054 that means you will add a new webpage,right..?

yes!

**Comment by Vanshiii203** [comment]
@myhacktech @Susmita-Dey Can I work on this issue?

**Comment by myhacktech** [comment]
> @myhacktech @Susmita-Dey Can I work on this issue?

@keerthana054 are u still working on this?

**Comment by myhacktech** [comment]
> @myhacktech @Susmita-Dey Can I work on this issue?

@Vanshiii203 yes u may go this issue
