### ISSUE TITLE
Implement animation library to the app using AOS

### ISSUE THREAD

**Issue by itsmdasifraza** [Susmita-Dey/Sukoon#450]
Main purpose of implementing animation is to make the app more attractive, checkout [official documentation](https://michalsnik.github.io/aos/)!

![Screenshot (160)](https://user-images.githubusercontent.com/58258334/192100546-81a7f05b-f2ec-4208-9282-993498d66664.png)

merge from #478

**Comment by myhacktech** [comment]
please explain properly

**Comment by itsmdasifraza** [comment]
I will add animation on elements like translate, scale and transform to move the elements
ex: fadeIn, fadeOut
