### ISSUE TITLE
Hamburger icon not visible on Talking therapy page

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#457]
Hamburger icon is not visible in the mobile layout form in the navbar of talking therapy page

Image:
![image](https://user-images.githubusercontent.com/96040322/191897646-5629d921-14b0-46f3-8251-8de0f8627f09.png)

**Comment by ShivanshAr97** [comment]
Please assign

**Comment by Vanshiii203** [comment]
> Hamburger icon is not visible in the mobile layout form in the navbar of talking therapy page
> 
> Image: ![image](https://user-images.githubusercontent.com/96040322/191897646-5629d921-14b0-46f3-8251-8de0f8627f09.png)

Fixed this in #415

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 It's a duplicate issue
