### ISSUE TITLE
Making signup page responsive

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#458]
I would like to make the signup page responsive

Image:
![image](https://user-images.githubusercontent.com/96040322/191898589-0447e0ee-ee2d-4922-9314-edee98b33259.png)

**Comment by ShivanshAr97** [comment]
Please assign

**Comment by ShravaniAK** [comment]
please assign

**Comment by Susmita-Dey** [comment]
@ShivanshAr97 Go ahead

**Comment by Susmita-Dey** [comment]
@ShravaniAK If he fails within 2 days, then you can take up the issue.
