### ISSUE TITLE
Add 3d books to the Reading Therapy's books section

### ISSUE THREAD

**Issue by Shivam-Katare** [Susmita-Dey/Sukoon#460]
Will, it looks good if we add 3D books instead of plain images, with some animations?

### Like this 👇

![Screenshot (25)](https://user-images.githubusercontent.com/91705825/191901365-57569546-8734-491b-9afc-5b2c941258f1.png)
![Screenshot (26)](https://user-images.githubusercontent.com/91705825/191901369-8644535b-f531-4b91-bead-f0980e51f558.png)
![Screenshot (27)](https://user-images.githubusercontent.com/91705825/191901371-9a8f7119-d561-43ce-b6a0-16d775269c86.png)

- If you think it will look good, then I am ready to take this issue.

**Comment by Susmita-Dey** [comment]
How would you add them?
in the form of image?

**Comment by Shivam-Katare** [comment]
No, I will remove these images and div, and instead of these, I will make those 3d books by using HTML and CSS with the hover effect.

![Screenshot (28)](https://user-images.githubusercontent.com/91705825/191905939-9c56227e-6a53-4e2f-849b-46978f85b3ca.jpg)

**Comment by Susmita-Dey** [comment]
Sounds interesting

**Comment by Susmita-Dey** [comment]
@Shivam-Katare Go ahead

**Comment by Shivam-Katare** [comment]
Hey, @Susmita-Dey I have implemented the 3D books. Is this look good?

### Preview

![Screenshot (34)](https://user-images.githubusercontent.com/91705825/191990793-013308ba-ee23-4154-94d5-911b364a65b5.png)

![Screenshot (33)](https://user-images.githubusercontent.com/91705825/191990859-a598f9be-0d35-4222-820d-914cd0aaab58.png)

But since there are some issues with raising the "PR" for this one, could you please merge my earlier "PR" #453?
