### ISSUE TITLE
Improving UI of asanas in yoga therapy page

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#462]
Asana section looks dull. I would like to improve its design.

Image:
![image](https://user-images.githubusercontent.com/96040322/191902991-27eeaa54-70d6-4c88-81cb-ff08d166bcea.png)

**Comment by ShivanshAr97** [comment]
Please assign

**Comment by Susmita-Dey** [comment]
A PR Is already there for yoga therapy UI. You have to wait to get assigned with this issue.
