### ISSUE TITLE
To improve UI of About Us page(photo frames and background)

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#47]
I would like to change, the UI of the About us page and add photo frames to respective admins of a project and also a beautiful background. assign me this issue.

![aboutus](https://user-images.githubusercontent.com/87818185/183094914-d76203af-54d3-4978-a2e2-1a9e303ded75.png)

**Comment by SachinMittal1766** [comment]
Hey @Kirankp25, Go Ahead
