### ISSUE TITLE
Placement of back button at 'Contact Us' page

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/Sukoon#486]
What:
The placement of the back button on the 'Contact Us' page is incorrect.
I suggest using a cross (x) button for going back or placing the button with alignment to the 'Submit' button.

Image:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/47862474/192114214-e9a85c55-0fec-488f-b107-190ce5e07255.png">

How to replicate:
1. Open the application.
2. Go to the 'Contact Us' section.
3. See the placement of 'back' button.

**Comment by bhattabhi013** [comment]
Please assign this issue to me.

**Comment by Susmita-Dey** [comment]
@bhattabhi013 To me it looks good.
