### ISSUE TITLE
To Remove repeated/unwanted Testimonials

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#487]
I would like to contribute to this project to make it more genuine and professional. Here in Testimonial, section two same testimonials are in conflict which creates the wrong message in the user's mind. I want to change it.Pls assign me these issue
![Screenshot (276)](https://user-images.githubusercontent.com/87818185/192114287-9e01d5f4-1e02-4144-8ce9-19c27c5d088b.png)

**Comment by Susmita-Dey** [comment]
@Kirankp25 duplicate issue.

**Comment by Kirankp25** [comment]
ok, but i didn't see these changes on site
