### ISSUE TITLE
Making contributing.md more readable

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/Sukoon#488]
What:
Every point listed should start from a new line to make it more readable.

Image:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/47862474/192114469-62f501c4-eb5f-4822-a28a-859b3f96ae4f.png">

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Are you an SSoC contributor?

**Comment by bhattabhi013** [comment]
Yes, earlier I was working on some other Flutter project.

**Comment by Susmita-Dey** [comment]
@bhattabhi013 Go ahead
