### ISSUE TITLE
Arranging the Heading & buttons for Audiobooks.

### ISSUE THREAD

**Issue by Stk-79** [Susmita-Dey/Sukoon#491]
'Play Now' Button is not properly placed.

![Screenshot (72)](https://user-images.githubusercontent.com/102925712/192115592-29a803c1-6277-49b0-80cd-c4df5357e818.png)
![Screenshot (73)](https://user-images.githubusercontent.com/102925712/192115595-1e423fab-2b71-41fd-a90c-9fb7a315c5b4.png)

**Comment by adityyaa-10** [comment]
Hi, can I work on this issue?

**Comment by myhacktech** [comment]
i am assigning,but u have to come with a better ui
