### ISSUE TITLE
Making text more readable on 'Yoga Therapy' page.

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/Sukoon#493]
What:
It is difficult to read the text on the 'Yoga Therapy' page.

Images:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/47862474/192118201-65e49402-6dff-430e-9128-1e7cd9ad98e8.png">

How to replicate:
1. Run the application.
2. Go to the 'Yoga therapy' page.
3. See the sub-title on the page.

**Comment by EmilieFlores** [comment]
Hello, I would like to be assigned this issue if it's still available. Thank you.

**Comment by bhattabhi013** [comment]
Hi @EmilieFlores,
Currently, this issue is assigned to me and I've also raised the PR for the same.

**Comment by bhattabhi013** [comment]
Hi, please close this issue as this is resolved.
