### ISSUE TITLE
Bug: Videos not properly aligned/ different sizes on 'yoga therapy' page.

### ISSUE THREAD

**Issue by bhattabhi013** [Susmita-Dey/Sukoon#494]
What:
Different sizes of the recommended videos on the 'yoga therapy' page.

Image:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/47862474/192118807-08514525-8d10-4dcd-9fc6-73669ab273f4.png">

How to replicate:

1. Run the application.
2. Go to the 'Yoga therapy' page.
3. See the sdifference between the first and second recommended video.

**Comment by adityyaa-10** [comment]
## @bhattabhi013 Is this issue fixed?


![image](https://user-images.githubusercontent.com/103577578/192127384-4f4cb705-f5f1-4783-a0c6-23cf55bb55a1.png)

seems fine to me

**Comment by bhattabhi013** [comment]
Hi Aditya, 
I think this is fixed in the latest commits.
