### ISSUE TITLE
Drastic changes in the Laugh Therapy due to some bugs making contents invisible.

### ISSUE THREAD

**Issue by Stk-79** [Susmita-Dey/Sukoon#499]
1.Previous and next arrows for Memes
2.Standups
3.Footer Content

This can be corrected reviewing the code properly.

![Screenshot (74)](https://user-images.githubusercontent.com/102925712/192130714-e8647cbb-b1cc-40ea-95ab-f7fdf67699ec.png)

**Comment by Susmita-Dey** [comment]
@Stk-79 go ahead

**Comment by Stk-79** [comment]
Should I close this issue as the page is updated and fixed? @Susmita-Dey @myhacktech 

This PR contains the fixes #501 .
