### ISSUE TITLE
Add CONTRIBUTING GUIDELINES

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#5]
Create a file named `CONTRIBUTING.md` that must contain some guidelines for beginners to contribute to this repo.

**Comment by MeghaKeshri** [comment]
I want to take it up.

**Comment by Roshani9731** [comment]
@Susmita-Dey Can I work on this ?

**Comment by Susmita-Dey** [comment]
> I want to take it up.

@MeghaKeshri Since it's been a long time and you didn't create any PRs, I'm assigning it to @Roshani9731 .

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Can I work on this ?

Sure, go ahead.

**Comment by Harsh3363** [comment]
Can i work on this?

**Comment by Susmita-Dey** [comment]
@Roshani9731 Are you working on this? If not, then I'll assign it to @Harsh3363 
Kindly inform me.

**Comment by kshitijmishra27** [comment]
hi @Susmita-Dey 
I want to work on this issue as I have some relevant experience in documentation
 https://onecompiler.com/cheatsheets/cpp
I created this one earlier 
so... i am the best match for this😄

**Comment by Harsh3363** [comment]
> hi @Susmita-Dey 
> I want to work on this issue as I have some relevant experience in documentation
>  https://onecompiler.com/cheatsheets/cpp
> I created this one earlier 
> so... i am the best match for this😄

Bro even I have writing experience 😅

https://www.geeksforgeeks.org/solidity-programming-erc-721-token/

**Comment by Susmita-Dey** [comment]
@Harsh3363 @kshitijmishra27 @Roshani9731 @MeghaKeshri Are you all SSOC participants?

**Comment by Harsh3363** [comment]
@Susmita-Dey can I work on this?

**Comment by SachinMittal1766** [comment]
@Harsh3363 Are you a SSOC Contributor ?

**Comment by Harsh3363** [comment]
> @Harsh3363 Are you a SSOC Contributor ?

Yes

**Comment by SachinMittal1766** [comment]
@Harsh3363 Go Ahead
