### ISSUE TITLE
To add new feature at home page

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Sukoon#50]
I would like to improve the features of the home page by adding some more attractive buttons and background it is very dull to look.
assign me this issue.

![mainpage](https://user-images.githubusercontent.com/87818185/183099162-ee7179d2-e1ec-461d-bac1-3190bcb0f204.png)

**Comment by SachinMittal1766** [comment]
First Complete issues assigned to you
https://github.com/Susmita-Dey/Sukoon/issues/40
https://github.com/Susmita-Dey/Sukoon/issues/43
https://github.com/Susmita-Dey/Sukoon/issues/47
