### ISSUE TITLE
Adding some more videos to Talking Therapy & styling.

### ISSUE THREAD

**Issue by Stk-79** [Susmita-Dey/Sukoon#514]
https://youtu.be/8jPQjjsBbIc

https://youtu.be/4ZQkYSpmOdU

https://youtu.be/71_NkXgAK1g

https://youtu.be/m3-O7gPsQK0

**Comment by Vanshiii203** [comment]
@Susmita-Dey I would like to work on this issue

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Go ahead.
