### ISSUE TITLE
Fix button in Reading Therapy Page

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#537]
Align the `read` button in center like others and remove the buttons of `Child Therapy` and `Spiritual Therapy` from this particular card.

![image](https://user-images.githubusercontent.com/79099734/195969645-e5b3ae8c-80b7-414f-889a-0fa3abb1f999.png)

Folks who want to take up this issue, comment below.

**Comment by Athi223** [comment]
Hey, I'd like to contribute to this
