### ISSUE TITLE
Add Transition to the Cards and buttons, Improve the Footer Section, Change the layout of home, about and services and add Team section with them.

### ISSUE THREAD

**Issue by Ashxsh1** [Susmita-Dey/Sukoon#54]

**Comment by imaaquibali** [comment]
@Ashxsh1 Go for it.

**Comment by vaibhavsharma1234** [comment]
I have one query like if u will put all the issues in one issue then what's left to do 
Just a query

**Comment by imaaquibali** [comment]
@vaibhavsharma1234 sorry i can't get you. Can you clear more plz?

**Comment by vaibhavsharma1234** [comment]
I just mean that if u look at this issue it can be divided into 5 diffrent issue and there is a chance that other people can also work on those but if all of these are combined into one issue then only one person can work that's it 
I am just stating my thoughts

**Comment by SachinMittal1766** [comment]
@Ashxsh1 Updates? If you are not working, Issue will be assigned to someone else

**Comment by Ashxsh1** [comment]
I Have added transition to the buttons and I'm working on the footer.

**Comment by Susmita-Dey** [comment]
@Ashxsh1 After you have done the changes kindy show me in discord and also before commiting any changes do `git fetch` and `git pull` and recent changes made

**Comment by Ashxsh1** [comment]
Sure!
