### ISSUE TITLE
Adding basic definition and Benefits of Reading in Reading Therapy Page

### ISSUE THREAD

**Issue by MohitNamdev22** [Susmita-Dey/Sukoon#542]
On the reading therapy page, upon scrolling content starts from articles. So, I'll add a section to define reading therapy and its Benefits of it.

**Comment by Susmita-Dey** [comment]
@MohitNamdev22 

@Vanshiii203 is also working on Reading therapy so make sure both of you don't conflict.

**Comment by MohitNamdev22** [comment]
Yeah sure @Susmita-Dey I'll coordinate with her 🫡
