### ISSUE TITLE
Use Flexbox to align the cards of Our Services Section, so that it can be responsive too and have better alignment

### ISSUE THREAD

**Issue by SujalSamai** [Susmita-Dey/Sukoon#55]

**Comment by Atharv-110** [comment]
Hello @SujalSamai please give the description about the problem and attach a screenshot of the preferred solution like issue #40

**Comment by SujalSamai** [comment]
> Hello @SujalSamai please give the description about the problem and attach a screenshot of the preferred solution like issue #40 
![image](https://user-images.githubusercontent.com/87236576/183126061-318cb2e7-a019-44dd-a313-4a06b14dd0fe.png)
As we can see, the services section has 6 cards, and they are not aligned and much of space is wasted in the second row. SO I would like to make the cards responsive so that they can get aligned column wise using flexbox. Something like this
![image](https://user-images.githubusercontent.com/87236576/183126577-51dcccca-8d7f-4ac5-88ed-c199d5ed7630.png)

**Comment by Atharv-110** [comment]
Go ahead @SujalSamai.
Assigned to you.
