### ISSUE TITLE
Removing extra space in the footer 

### ISSUE THREAD

**Issue by Vanshiii203** [Susmita-Dey/Sukoon#550]
Removing the extra space below the footer
https://user-images.githubusercontent.com/94471189/196448275-ef21f150-7d53-4c7a-80ae-a67fd95969f6.mp4

**Comment by devpawann** [comment]
Can I take this issue?

**Comment by Susmita-Dey** [comment]
@Vanshiii203 How will you remove the extra space in the footer? Don't you think that things will gather together in one place conflicting with each other?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 How will you remove the extra space in the footer? Don't you think that things will gather together in one place conflicting with each other?
I am talking about this space 
![Screenshot (486)](https://user-images.githubusercontent.com/94471189/196739056-7ce3d90f-58d7-435e-bd1d-8b346ed25550.png)
I'll just adjust the height of footer
