### ISSUE TITLE
feat: github action for greeting FTCs

### ISSUE THREAD

**Issue by kumarsonsoff3** [Susmita-Dey/Sukoon#553]
### Description

**What do you think of adding a GitHub action for greeting the first-time contributors on the project!?**

It seems more engaging and encouraging to the new contributors, and to the ones who are getting started with open-source!! 🙂

### Screenshots

Some thing like this! 

![image](https://user-images.githubusercontent.com/88786642/197375246-20d133fb-3314-42b1-9bfb-51de705ad1e9.png)

### Additional information

I would love to work on this issue!

**Comment by Susmita-Dey** [comment]
@kumarsonsoff3 Go ahead
