### ISSUE TITLE
Improving UI on the Audio therapy page 

### ISSUE THREAD

**Issue by SahilDahekar** [Susmita-Dey/Sukoon#57]
- Will remove the rounded corners and may adding padding , margin and other UI improvements.

![Screenshot 2022-08-06 000106](https://user-images.githubusercontent.com/97726887/183139742-244a3ee6-dbc7-42ca-ae18-15215eb33542.png)

- Improve the styling applied on each book card like font color. 
- Overall improving the designing of the page.

![Screenshot 2022-08-06 000136](https://user-images.githubusercontent.com/97726887/183139839-fdb13bc1-6947-4818-9b71-a0666e2f6c60.png)

**Comment by SahilDahekar** [comment]
can i work on this issue?

**Comment by SachinMittal1766** [comment]
Yes, Go for it

**Comment by SahilDahekar** [comment]
Should I fetch from the SSOC branch or the main branch

**Comment by Susmita-Dey** [comment]
> -Should I fetch from the SSOC branch or the main branch? -Should I check the copy only the main branch during fork?

fetch from main branch and copy the main branch only
