### ISSUE TITLE
Missing a space

### ISSUE THREAD

**Issue by FahimFBA** [Susmita-Dey/Sukoon#570]
### Description

There is a space missing between `West Bengal,` and `India`.

### Screenshots

![Annotation 2023-01-03 181839](https://user-images.githubusercontent.com/64195132/210355972-b64b4084-8519-4a91-8449-3b60726fd009.png)

### Additional information

I am ready to fix this small issue by adding a Pull Request.

**Comment by Susmita-Dey** [comment]
@FahimFBA Do you wanna work on this issue?

**Comment by FahimFBA** [comment]
> @FahimFBA Do you wanna work on this issue?

Yes.
