### ISSUE TITLE
Scroll broken in firefox

### ISSUE THREAD

**Issue by shivanshu-semwal** [Susmita-Dey/Sukoon#571]
### Description

Scrolling don't work on pages except the home screen. For e.g. <https://sukoon-stress-free.netlify.app/html/yogatherapy.html>. This issue is related to firefox only.

**Comment by Susmita-Dey** [comment]
Hello @shivanshu-semwal Kindly attach an ss related to the problem

**Comment by sourabh32** [comment]
There is no issue in my case.
<img width="238" alt="Screenshot 2023-12-05 211839" src="https://github.com/Susmita-Dey/Sukoon/assets/114211264/ee2a1c4a-98cb-43f9-b956-f53a377e750a">
