### ISSUE TITLE
Adding text typing effect 

### ISSUE THREAD

**Issue by Arjundotadex** [Susmita-Dey/Sukoon#572]
### Description

Adding a text typing effect on the home page on the below text.

"The one-step solution to get relief from your stress.
Live a stress-free life!"

### Screenshots

![image](https://user-images.githubusercontent.com/103199408/211026551-36e0f601-1223-45d8-aa39-5b4745fe0b3c.png)

### Additional information

The typing effect will be created using CSS & Javascript

**Comment by Arjundotadex** [comment]
![image](https://user-images.githubusercontent.com/103199408/211033988-805ceb3e-6416-4e82-9baa-2e2025798b71.png)

Final Output

**Comment by Arjundotadex** [comment]
![image](https://user-images.githubusercontent.com/103199408/211034880-2fbcc5cc-791e-477d-9529-510314e35127.png)

Final Output

**Comment by sarah-adewale** [comment]
hey @Arjundotadex i'd like a crack at this. Could you assign it to me?

**Comment by Arjundotadex** [comment]
> hey @Arjundotadex I'd like a crack at this. Could you assign it to me?
I myself am not assigned because code review is still pending by Susmita-Dey.
