### ISSUE TITLE
[FEATURE] I want to reduce the font-size of the navbar texts 

### ISSUE THREAD

**Issue by mohammadshaad** [Susmita-Dey/Sukoon#574]
### Description

I want to reduce the font-size of the texts in the navbar as it is looking a bit odd. Kindly assign me this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/89409389/211160856-8a52e2cf-8803-4d18-ad3e-1421315df0ce.png)

**Comment by sarah-adewale** [comment]
hello @mohammadshaad i'd like to work on this issue. Could you assign it to me?

**Comment by mohammadshaad** [comment]
@Susmita-Dey kindly assign me this issue
