### ISSUE TITLE
[FEATURE] Social links in the footer section--> improvement

### ISSUE THREAD

**Issue by RitikRG** [Susmita-Dey/Sukoon#578]
### Description

Currently if you hover over the social links in the footer section the icons change color.

But every icon changes to the same color, what I am suggesting is to give each link a specific color like twitter's blue too the twitter icon and also a bit of scaling on hovering.

If you like the idea, can I work on the feature?

### Screenshots

![Screenshot (344)](https://user-images.githubusercontent.com/106656982/212133304-259b447d-b182-4fe4-815e-4bbf14cff87d.png)

**Comment by jaseel-koolath** [comment]
That sounds wonderful

**Comment by RitikRG** [comment]
@Susmita-Dey Should I work on this ?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Should I work on this ?

Go ahead

**Comment by RitikRG** [comment]
Ok I will do this and create a pr

**Comment by RitikRG** [comment]
@Susmita-Dey I have completes a task and raised the [pr#581](https://github.com/Susmita-Dey/Sukoon/pull/581)  please it out.

Thanks

**Comment by anujpatel2899** [comment]
Can I still contribute to this ?

**Comment by aashayk18** [comment]
Is this still open for contribution?
