### ISSUE TITLE
want to give hover effect in home page button

### ISSUE THREAD

**Issue by rani620** [Susmita-Dey/Sukoon#58]
At home page hover is not good very  simple I want to modify it plz.  can assig it to me.
![Screenshot (822)](https://user-images.githubusercontent.com/96174308/183145874-d71ff5df-49d1-4de6-9991-aebdc4fc12a4.png)

**Comment by SachinMittal1766** [comment]
Go Ahead

**Comment by AnushkaMittal21** [comment]
Can I be assigned this issue? @SachinMittal1766

**Comment by SachinMittal1766** [comment]
@AnushkaMittal21 Are you a SSOC participant ?

**Comment by fykaa** [comment]
@SachinMittal1766 Assign this issue to me, I am a SSOC participant

**Comment by rani620** [comment]
> Are you an SSOC participant?

yes sir I am a SSOC participant. becoz i created this issue so plzzz assign it to me .

**Comment by Susmita-Dey** [comment]
@rani620 Go ahead and create a PR.

**Comment by rani620** [comment]
ok maam
