### ISSUE TITLE
Closing the navbar whenever a link is clicked in navbar in mobile view.

### ISSUE THREAD

**Issue by rohinish404** [Susmita-Dey/Sukoon#583]
### Description

Whenever a link to new section is clicked in the navbar in mobile view, the navbar stays in that place itself and the user has to close the navbar everytime they move to different section. So i think it should get closed by itself after reaching the section. It will help in improving user experience.

https://user-images.githubusercontent.com/92542124/213931444-bb9028e4-75a0-4013-9ac5-9be4fa294cbc.mov

**Comment by chs-mix** [comment]
Could I please work on this?

**Comment by rohinish404** [comment]
@chs-mix If the maintainer approves this issue, you can ask them to assign it to you.

**Comment by rohinish404** [comment]
> @Susmita-Dey @rohinish404 is the issue still open? If yes, can i contribute to it? Thank you in advance.

Yeah you can take up this issue! Just look around in the website that is this issue still relevant or not.

**Comment by gopaal24** [comment]
@rohinish404 the issue still seems unsolved. So, should i wait for @Susmita-Dey to assign it to me or can i go ahead and open a PR once it is done?

**Comment by rohinish404** [comment]
> @rohinish404 the issue still seems unsolved. So, should i wait for @Susmita-Dey to assign it to me or can i go ahead and open a PR once it is done?

I've unassigned myself. You can wait to get assigned but if in 2 3 days you don't get any response just make a pr and mention this issue in that! All the best :)

**Comment by sourabh32** [comment]
Fixed this issue #[637]
