### ISSUE TITLE
Making Spiritual therapy page responsive

### ISSUE THREAD

**Issue by shank1729** [Susmita-Dey/Sukoon#587]
### Description

Improving the UI in spiritual therapy page. The text under the heading "spirituality" is not responsive and in the events section the boxes are not centralized in mobile view. I can work on this and make the changes.

### Screenshots

![image](https://user-images.githubusercontent.com/104124777/218322344-fbd96aa7-ed51-42d8-bb02-d1892f69ff90.png)
![image](https://user-images.githubusercontent.com/104124777/218322429-3499716f-e4b9-4720-9c20-0b1656237ad1.png)

**Comment by Saideepak01** [comment]
@Susmita-Dey fixed this issue can you please review this pr https://github.com/Susmita-Dey/Sukoon/pull/591

**Comment by Aravinthan-J** [comment]
@Susmita-Dey - this issue is fixed -  Can you review this pr #596
