### ISSUE TITLE
In members , image get expandable

### ISSUE THREAD

**Issue by dev-mohanraj** [Susmita-Dey/Sukoon#589]
### Description

Need to change css

### Screenshots

<img width="1116" alt="Screenshot 2023-02-22 at 4 05 41 PM" src="https://user-images.githubusercontent.com/84064669/220595685-a0b8c844-86ad-41c6-a708-f70efb78909d.png">

**Comment by anujpatel2899** [comment]
Can I work on this, and can you assign me this issue?

**Comment by RahulRana701** [comment]
hey @dev-mohanraj I would like to work on this issue can you assign it to me..

**Comment by Susmita-Dey** [comment]
Duplicate issue as it's already been fixed now via #590
