### ISSUE TITLE
missing space 

### ISSUE THREAD

**Issue by sumitshinde-84** [Susmita-Dey/Sukoon#592]
### Description

required space in stressfree 

![Screenshot (56)](https://user-images.githubusercontent.com/110285294/221403877-bb755fe9-41ce-44f4-8d3c-28fd6e8f1ea0.png)

### Screenshots

expected output should look like this 

![Screenshot (58)](https://user-images.githubusercontent.com/110285294/221403908-1fda65a2-dc1c-45b0-8df7-05bc06f6197f.png)

### Additional information

check it i have fixed it PR  #593

**Comment by RahulRana701** [comment]
hey @sumitshinde-84 I would like to work on this issue can you assign it to me..

**Comment by sumitshinde-84** [comment]
Please check out PR #593
Issue is already fixed
