### ISSUE TITLE
empty Form data is getting submitted

### ISSUE THREAD

**Issue by 777Prabhjot** [Susmita-Dey/Sukoon#599]
### Description

In the contact us page form data is getting submitted even if we only add spaces in the input fields.

**Video**

https://user-images.githubusercontent.com/68184118/232468627-5d395467-af72-41e0-badf-ecdf63ed5c86.mp4

**Comment by kunalvirk** [comment]
Hi,

Can I work on this issue?

Thanks,
Kunal
