### ISSUE TITLE
Removing the white background from the logo.

### ISSUE THREAD

**Issue by rakshitgondwal** [Susmita-Dey/Sukoon#60]
By removing the white background of the logo, it would look professional and will have more visibility.
The go stressfree line is nearly invisible because of the white background as it limits us with the size of the logo. 
By removing the white background and updating it with the new one, we will be able to resize the logo too.

I have a good experience with photoshop and illustrator both. I can work on this if you wanna go on with this issue.

![Screenshot (204)](https://user-images.githubusercontent.com/98955085/183219737-4567abf0-2e3f-4056-b6a1-121efd4b7605.png)
![Screenshot (203)](https://user-images.githubusercontent.com/98955085/183219739-417d6c92-f2d6-4efe-b385-0c204c2d0caf.png)

**Comment by SachinMittal1766** [comment]
@Susmita-Dey Pls look into it

**Comment by Susmita-Dey** [comment]
@SachinMittal1766 Good observation. Go ahead and make a PR.

**Comment by Susmita-Dey** [comment]
@rakshitgondwal Good observation. Go ahead.

**Comment by rakshitgondwal** [comment]
@Susmita-Dey what do you think about this one?
![Sukoonpng](https://user-images.githubusercontent.com/98955085/183246018-45b78673-7614-4bbe-ad01-e3921043d92d.png)

**Comment by rakshitgondwal** [comment]
@Susmita-Dey What do you think about this one
![SukoonPNGlogo](https://user-images.githubusercontent.com/98955085/183246717-825cbece-879b-4cf5-9870-b7209108da2f.png)
?

**Comment by rakshitgondwal** [comment]
@SachinMittal1766 I was wondering if you could look into this too.

**Comment by rakshitgondwal** [comment]
@Susmita-Dey
