### ISSUE TITLE
Issue With Mobile Responsiveness

### ISSUE THREAD

**Issue by 0rigin-c0de** [Susmita-Dey/Sukoon#607]
### Description

Hey @Susmita-Dey ,
I want to tell you that this beautiful website is not fully responsive to mobile devices 

### Screenshots

![sukoon](https://github.com/Susmita-Dey/Sukoon/assets/106311923/5bbfb030-320f-4866-9fc5-db2e3f4cc954)
![sukoon2](https://github.com/Susmita-Dey/Sukoon/assets/106311923/d39d5ae3-66f9-4dbb-949c-a7b1a6092caf)

### Additional information

@Susmita-Dey Kindly Assign it to me

**Comment by Utkarsh3128** [comment]
I have submitted a PR. Please review it.
