### ISSUE TITLE
Page Not Found on Clicking Spiritual Therapy in Footer

### ISSUE THREAD

**Issue by Sumonta056** [Susmita-Dey/Sukoon#611]
## How Regenerate the ISSUE
- Go to Footer 
- Click Spiritual Therapy
- Now you can see the error

### Screenshots

![image](https://github.com/Susmita-Dey/Sukoon/assets/61287791/a6177f5a-d6a3-46a9-94d3-dc0f5198f07e)
![image](https://github.com/Susmita-Dey/Sukoon/assets/61287791/5d33dee3-9ddc-42d7-973f-a7d8bf255e80)

**Comment by GrandmasterGogo** [comment]
Hi,
I am interested in being assigned to this issue. I am confident that I can resolve this issue.
Please let me know if you have any questions or if there is anything else that I can do to help.
Thanks,
GrandmasterGogo

**Comment by Yadav97** [comment]
Hi,
I am interested in being assigned to this issue.i have experience to solve this type of issues 
thanks,
Yadav97
