### ISSUE TITLE
Linking of Certain pages

### ISSUE THREAD

**Issue by ASP124** [Susmita-Dey/Sukoon#617]
### Description

When clicked on back button in Contact us page it give this error shows there is no linking of pages and same is the issue with login and signup page

### Screenshots

![Screenshot (225)](https://github.com/Susmita-Dey/Sukoon/assets/86464479/67f37c22-d83c-41a8-9382-4da6aa8864cf)
![Screenshot 2023-10-19 012241](https://github.com/Susmita-Dey/Sukoon/assets/86464479/27139381-90c8-4976-8e2b-1beb5d3c88a9)

### Additional information
I would love to work on this issue

_No response_

**Comment by shubhamnimbalkkar** [comment]
Hello I would love to contribute this project

**Comment by FortuneBush** [comment]
Hello, I would like to try to solve this problem. Can you assign this problem to me?@ASP124

**Comment by ASP124** [comment]
@FortuneBush actually it was just a code glitch otherwise its working fine
