### ISSUE TITLE
Number of services

### ISSUE THREAD

**Issue by ASP124** [Susmita-Dey/Sukoon#618]
### Description

There are a total of 9 number of services in your home page but in the footer section there is only 7 services.

### Screenshots

![Screenshot 2023-10-19 020030](https://github.com/Susmita-Dey/Sukoon/assets/86464479/829f5e8d-8e33-47d0-bb0e-b323d1d64365)
![Screenshot 2023-10-19 020042](https://github.com/Susmita-Dey/Sukoon/assets/86464479/4a690203-fe87-4690-be50-90b818491702)
![Screenshot (226)](https://github.com/Susmita-Dey/Sukoon/assets/86464479/56bb8016-6c6d-4cd3-ba24-6dca44ded6ee)

### Additional information

I would like to update it sequentially

**Comment by Susmita-Dey** [comment]
Hey @ASP124 Work on it
