### ISSUE TITLE
i would like to add a automatic slider on the hero section of the main page 

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Susmita-Dey/Sukoon#63]

**Comment by SachinMittal1766** [comment]
Explain a bit more about the issue. Then, I will assign it to you

**Comment by vaibhavsharma1234** [comment]
Currently there is only one image
Wouldn't it be nice that image automatic changes 
Like a slider but it will be automatically

**Comment by imaaquibali** [comment]
@vaibhavsharma1234 start working on it.

**Comment by vaibhavsharma1234** [comment]
Thanks for assigning please add the difficulty of issue tag also

**Comment by vaibhavsharma1234** [comment]
Currently working on this just a little busy due to college
