### ISSUE TITLE
Yoga Therapy

### ISSUE THREAD

**Issue by AnushkaMittal21** [Susmita-Dey/Sukoon#66]
Can I create a yoga therapy page?
Will contain all the services, tricks and techniques for yoga therapy. Will be a responsive page.

**Comment by Susmita-Dey** [comment]
Yes, go ahead

**Comment by Susmita-Dey** [comment]
@AnushkaMittal21 First tell me are you an SSOC participant?

**Comment by AnushkaMittal21** [comment]
> 

Yes!
