### ISSUE TITLE
Add more music In Audio Therapy page | SSOC 2022 Participant

### ISSUE THREAD

**Issue by Surya8991** [Susmita-Dey/Sukoon#70]
I would like add a section for Nature Sounds which would be calm and soothing to mind and also make the nature sound section responsive in both pc and mobile.
Do Assign it to me.

**Comment by Susmita-Dey** [comment]
@Surya8991 Do you have any API in your mind?

**Comment by Surya8991** [comment]
No I thought let me use spotify but will search for api and will suggest u if I could find one
