### ISSUE TITLE
Improving Contact page UI for SSOC Contribution

### ISSUE THREAD

**Issue by ShivanshAr97** [Susmita-Dey/Sukoon#72]
**Improving the user interface of contact page**

![image](https://user-images.githubusercontent.com/96040322/183242719-0a3fbdcc-d24d-49a9-8547-6e18466896af.png)

**Comment by SachinMittal1766** [comment]
Elaborate the issue

**Comment by ShivanshAr97** [comment]
Providing margin and padding, adding image, improving button style(matching with other buttons), adding message placeholder, and changing font size.

**Comment by Akayush-17** [comment]
> Providing margin and padding, adding image, improving button style(matching with other buttons), adding message placeholder, and changing font size.

Hey I would like to work on this

**Comment by ShivanshAr97** [comment]
@Akayush-17 issue is already solved

**Comment by ShivanshAr97** [comment]
@siddhi-244 @SachinMittal1766 Why is this still open?
This issue is already merged in the website

https://github.com/Susmita-Dey/Sukoon/pull/82
