### ISSUE TITLE
improvise the style of heading

### ISSUE THREAD

**Issue by 29Aastha** [Susmita-Dey/Sukoon#73]
I m a SSOC participant 

-add gradient to h1 
- add animation to gradient 
- change font style of h1

**Comment by Susmita-Dey** [comment]
@29Aastha Check issue #38 Your issue seems to be duplicate.

**Comment by 29Aastha** [comment]
@Susmita-Dey  issue#38 is already closed so can you assign me this issue ? 
I am planning to apply animated gradient to the text on home page

https://user-images.githubusercontent.com/101136877/183277033-3c7985b8-4b4f-4e6c-ba54-297340e1b644.mp4

<img width="838" alt="image" src="https://user-images.githubusercontent.com/101136877/183277065-0fb554c8-af82-4bcb-b693-4f8304edb7d7.png">

**Comment by SachinMittal1766** [comment]
Nice
