### ISSUE TITLE
Improve Footer Design

### ISSUE THREAD

**Issue by fykaa** [Susmita-Dey/Sukoon#74]
Please Assign me this Issue 
SSOC'22 Participant

Changing Aesthetics and designing of the footer using css and html and altering design.
Somewhat like this:
![Screenshot (679)](https://user-images.githubusercontent.com/97490463/183244975-ebdc3e73-c320-4f7e-9ba7-617eefbe2ad7.png)

**Comment by siddhi-244** [comment]
Lgtm
