### ISSUE TITLE
Navbar for mobile responsiveness

### ISSUE THREAD

**Issue by jibreel1** [Susmita-Dey/Sukoon#8]
I want to work on navbar for mobile responsiveness.

**Comment by Susmita-Dey** [comment]
> I want to work on navbar for mobile responsiveness. 

@jibreel1 Go ahead.

**Comment by jibreel1** [comment]
> > I want to work on navbar for mobile responsiveness.
> 
> @jibreel1 Go ahead.

I have pushed my branch (jibreel1) to my repo, I wonder why it isn't showing on yours. what am I doing wrong?

**Comment by Susmita-Dey** [comment]
@jibreel1 You have create a pull request

**Comment by jibreel1** [comment]
> @jibreel1 You have to create a pull request

It's telling me there isn't anything to compare. What could be wrong?

**Comment by Susmita-Dey** [comment]
> It's telling me there isn't anything to compare. What could be wrong?
I guess you are comparing in your forked repo which is wrong.
