### ISSUE TITLE
Improvise and enhance the UI of reading therapy Page

### ISSUE THREAD

**Issue by Monishobaid** [Susmita-Dey/Sukoon#80]

**Comment by Monishobaid** [comment]
Can you assign this to me?

**Comment by Susmita-Dey** [comment]
@Monishobaid Go ahead

**Comment by popcandy1x** [comment]
Can I take this issue and work on it as it has been 3 days and no update has been provided on it.

**Comment by Susmita-Dey** [comment]
@Monishobaid Are you still working on this issue? 
If not, then I'll assign it to @popcandy1x

**Comment by Monishobaid** [comment]
sorry for not updating I got stuck with few other works sure @popcandy1x can go ahead with this issue on work on it

**Comment by Susmita-Dey** [comment]
@popcandy1x Go ahead but while making changes show me on discord before creating a final PR.

**Comment by popcandy1x** [comment]
Ok👍
