### ISSUE TITLE
Want to add Login section. 

### ISSUE THREAD

**Issue by 09khu** [Susmita-Dey/Sukoon#81]

**Comment by Susmita-Dey** [comment]
Do you wanna make the complete backend or only make a simple login and registration page?

**Comment by 09khu** [comment]
I can also do backend but only in php.

**Comment by arvindbatham600** [comment]
I want to work on this issue

**Comment by imaaquibali** [comment]
@09khu start working on it.

**Comment by imaaquibali** [comment]
@arvindbatham600 sorry brother it will assigned to @09khu raise another issue. Happy coding xd.

**Comment by arvindbatham600** [comment]
okii

**Comment by 09khu** [comment]
I have to do both backend and frontend or only frontend?

**Comment by akanksha0812** [comment]
please assign this issue to me

**Comment by Susmita-Dey** [comment]
> please assign this issue to me

If @09khu fails to add, then you can work on it.
