### ISSUE TITLE
Improve grammatical errors in description

### ISSUE THREAD

**Issue by soumil1** [Susmita-Dey/Sukoon#83]
I discovered a few grammatical errors in the project description. I can make it better.

**Comment by Susmita-Dey** [comment]
@soumil1 Go ahead

**Comment by soumil1** [comment]
@Susmita-Dey Can you check [4b8c79e](https://github.com/Susmita-Dey/Sukoon/pull/105/commits/4b8c79e33d75114800cfa63e3285e05ad85c21a3)
