### ISSUE TITLE
Improving the file structure

### ISSUE THREAD

**Issue by vedant-3010** [Susmita-Dey/Sukoon#84]
Many files have the same name, making it difficult to navigate and also changing internal CSS to external CSS. Basically structuring the codebase.
Can I work on this?

**Comment by Susmita-Dey** [comment]
@dare-devilll Go ahead

**Comment by Vanshiii203** [comment]
@Susmita-Dey  Can I work on this issue?

**Comment by Susmita-Dey** [comment]
@dare-devilll Are you still working on this issue? Also, are you an SSoC participant?

**Comment by dare-devilll** [comment]
@Susmita-Dey Yes I am SSOC participant, I was thinking of completing this issue at the end of ssoc, because everybody is making changes daily. I structured it once and the next day someone again wrote internal CSS.
Can we wait?

**Comment by Susmita-Dey** [comment]
@dare-devilll We can wait but you will lose your contribution. What can be done is to do it in the last week of contribution period and in the meanwhile we can stop taking contributions for a day or some hours.

**Comment by dare-devilll** [comment]
Ok.
When is the contribution period ending?

**Comment by Susmita-Dey** [comment]
@dare-devilll On 1st October
