### ISSUE TITLE
Button Transitions are not smooth

### ISSUE THREAD

**Issue by AnshuMishra01** [Susmita-Dey/Sukoon#92]
Button Transitions are not smooth, I want to make them work smoothly.

![image](https://user-images.githubusercontent.com/95041038/183271877-9733230d-818b-45bb-978c-a5fa5da5bb10.png)

**Comment by SachinMittal1766** [comment]
Go for it

**Comment by Susmita-Dey** [comment]
@AnshuMishra01 Are you gonna work on it? 
> If yes, then why did you close it?
