### ISSUE TITLE
Alot of Senseless space in the Navbar

### ISSUE THREAD

**Issue by AnshuMishra01** [Susmita-Dey/Sukoon#93]
Alot of Senseless space in the Navbar, Which make it look bad, I want to remove those spaces.

![image](https://user-images.githubusercontent.com/95041038/183271901-fdb7affc-c04e-4036-b6e0-30138f208cb6.png)

**Comment by SachinMittal1766** [comment]
Explain a bit more about the issue & what you want to change

**Comment by Sampurankishoresrivastava** [comment]
Please assign this to me.
Here are some sample of nav-bar made by me.
[Files.zip](https://github.com/Sulagna-Dutta-Roy/Webeginner-projects/files/9283473/Files.zip)

**Comment by Susmita-Dey** [comment]
@Sampurankishoresrivastava I'm assigning it to you for now but while making the changes show me on discord before making any PR.

**Comment by Sampurankishoresrivastava** [comment]
Ye Sure!
