### ISSUE TITLE
Modify Coming Soon Page

### ISSUE THREAD

**Issue by SachinMittal1766** [Susmita-Dey/Sukoon#96]
UI of "[Coming Soon](https://sukoon-stress-free.netlify.app/html/comingsoon)" page is not that good. 
If any Contributor wants to work, I can assign it to you.

**Comment by vaibhavsharma1234** [comment]
I want to work

**Comment by SachinMittal1766** [comment]
First complete assigned issues: https://github.com/Susmita-Dey/Sukoon/issues/64, https://github.com/Susmita-Dey/Sukoon/issues/63, https://github.com/Susmita-Dey/Sukoon/issues/42

**Comment by YasirObaibullah99** [comment]
I can do if its not assigned to any one

**Comment by vaibhavsharma1234** [comment]
ok sir 
the 42 one is causing problem in merge conflict 
it will be solved till night

**Comment by popcandy1x** [comment]
Sir can i work on this issue
