### ISSUE TITLE
"Code of Conduct" link not working properly

### ISSUE THREAD

**Issue by SachinMittal1766** [Susmita-Dey/Sukoon#97]
Link should take user to https://github.com/Susmita-Dey/Sukoon/blob/main/CODE_OF_CONDUCT.md
If anyone wants to work Comment below, I will assign to you

**Comment by vaibhavsharma1234** [comment]
I will do it please assign

**Comment by SachinMittal1766** [comment]
First complete assigned issues: https://github.com/Susmita-Dey/Sukoon/issues/64, https://github.com/Susmita-Dey/Sukoon/issues/63, https://github.com/Susmita-Dey/Sukoon/issues/42

**Comment by MohitNamdev22** [comment]
May I fix this issue?

**Comment by SachinMittal1766** [comment]
@MohitNamdev22 Go for it
